### ISSUE TITLE
Google play blocked my example =\

### ISSUE THREAD

**Issue by IlyaEremin** [googlesamples/android-play-billing#1]
I followed readme instruction and after publishing on alpha channel my app was blocked.
From email:

Your app is in violation of the intellectual property and impersonation or deceptive behavior provisions of the Content Policy.

If you have the owner’s permission to use this content, please contact our policy support team and attach verifiable and accepted proof of permission.
...

It is sad =\

**Comment by PaulRashidi** [comment]
Please use the instructions in the communication you received.

**Comment by clarle** [comment]
In case anyone is curious, I ran into the same issue.

I just attached the LICENSE file from this repository to the appeal, said it was part of a `googlesamples` repository, and that I was only going to publish to the alpha channel anyway.

My appeal was accepted in ~36 hours and I was able to publish to the alpha channel after that.  It'd be great if something could be done to not have this happen, though.  It definitely makes learning in-app billing something much more time-consuming.

**Comment by vizvamitra** [comment]
I've just faced the same problem: my app (slightly modified for testing purposes) was just banned for violation of impersonation policy though it wasn't publicly acceptable. I've just sent the appeal. Even if it'll be accepted, that's a shame for the Google's support team

Also thank you guys for the great sample code with lots of good comments ^_^
