### ISSUE TITLE
No longer possible to get subscription SKU details with queryInventoryAsync

### ISSUE THREAD

**Issue by kplatfoot** [googlesamples/android-play-billing#10]
As of commit https://github.com/googlesamples/android-play-billing/commit/4ee7eb837c4685ac0997d1fa6370eb0114e60eb9, `queryInventoryAsync` cannot retrieve SKU details for subscription products. The reason is that `queryInventory` now uses the `moreSubsSkus `argument when querying for `ITEM_TYPE_SUBS.` Prior to the change, both calls to `querySkuDetails` used `moreItemSkus.` Though the new code is correct, it exposes a separate problem, which is that `queryInventoryAsync` takes only a _single_ list of SKUs to query. It used to be possible to include in that list SKUs for both in-app and subscription purchases, and everything worked (perhaps the service's `getSkuDetails` method was filtering them?).

I have a patch ready that fixes the problem by adding a `moreSubsSkus` parameter to `queryInventoryAsync` and passing it through to `queryInventory`. I've also cleaned up the signatures of the `queryInventory*` methods. There were some overrides that didn't make sense, for example: `queryInventoryAsync(querySkuDetails, QueryInventoryFinishedListener.` The value of the first argument is effectively ignored, because there's no way to actually pass any SKUs to query.

**Comment by adennie** [comment]
I've noticed the same problem and fixed it locally the same way as described by kplatfoot; would be nice to get this fixed in the sample.
