### ISSUE TITLE
Manual renewal of subscriptions

### ISSUE THREAD

**Issue by iflp** [googlesamples/android-play-billing#105]
Hi, according to https://developer.android.com/google/play/billing/billing_subscriptions.html manual renewal of subscriptions is possible. How do I go about doing this? 

I can't find anymore information about it anywhere. When I try to purchase an already existing subscription again, I get Error: You've already subscribed to xxx, with a link to manage subscriptions. 

If someone can point me in the right direction it would be much appreciated. Thanks!

**Comment by pfmaggi** [comment]
Please refer to ClassyTaxy.

Closing as obsolete.

Please reopen if you think this issue is still relevant.
