### ISSUE TITLE
onPurchasesUpdated list not updated after consuming item

### ISSUE THREAD

**Issue by Chezlui** [googlesamples/android-play-billing#111]
Hi,

I am using the BillingManager class from the Trivial V2 sample app in my own app with minor basic modifications. 

After a successfully initiated purchase flow, onPurchasesUpdated is called. Inside my custom listener, I check if in the list of purchases there is any consumable item and then call immediately consumeAsync.

Once it is consumed I buy again the same item, the issue here is that when onPurchasesUpdated is called after the buying, the "purchases list" returned contains both the newly purchased item and the consumed previous one.

As you can see in the image, the list contains 3 items with the same productId, 2 of them already consumed but added to the list when onPurchasesUpdated is triggered.

![image](https://user-images.githubusercontent.com/4120243/33916140-a4e2cbb4-dfa7-11e7-867d-a436a8c3a9b8.png)

If I repeat the process, the list grows until Billing Manager is destroyed.

**Comment by vitovalov** [comment]
I face the same situation. How did you solve it? @Chezlui
