### ISSUE TITLE
How to find purchase state in new version, since Purchase.getPurchaseState() is no longer available?

### ISSUE THREAD

**Issue by DrkCore** [googlesamples/android-play-billing#113]
In old version `com.android.billingclient:billing:dp-1` we could use `Purchase.getPurchaseState()` method to get the state of it. But this is no longer available in the new version `com.android.billingclient:billing:1.0`.

In docs [Play Billing Library: Querying for purchased items](https://developer.android.com/google/play/billing/billing_library.html) it says that:

> You can then call a variety of methods on the Purchase object to view relevant information about the item, such as its **【【【purchase state】】】** or time. To view the types of product detail information that are available, see the list of methods in the Purchase class.

But, as you can see, there is NO such a thing.

Another question is, how could we get those `CANCELED` and `REFUND` ones?

According to the docs, we could use `BillingCliend.queryPurchases()` to get `PURCHASED` items, and use `BillingCliend.queryPurchaseHistoryAsync()` to get all items. With this two methods we could know which item is NOT `PURCHASED`, but never will we know what is it in the end.

**Comment by MrBIMC** [comment]
How did you manage to solve this issue?

**Comment by TobiasReich** [comment]
Good question. I was looking for the same info. Any idea yet?

**Comment by MrBIMC** [comment]
From what I understood by reading different stuff in google, google really doesn't want in-apps to be refundable and you should not handle refunds with few rare exceptions. 

From inside of the app perspective, you should respect the purchase no matter was it refunded or not and just let it be. 

Technically, yes, there will be few situations where it will lead to users getting in-app for free, but these would be rare and you can't do anything about it. 

So the only adaptation I did is added clause regarding refunds policy to app's license agreement and I stated that refunds won't be issued unless they've been granted by google. And google's refund policy regarding in-apps is kinda similar and reads as "we don't issue refunds with few rare exceptions".

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please upgrade to the latest version of the library to find `Purchase.getPurchaseState()`. If the issue is still not resolved, please post this question on StackOverflow. Presently we are reserving Github for questions specifically about the samples so we can better serve you.
