### ISSUE TITLE
Purchase finished: IabResult: IAB returned null purchaseData or dataSignature (response: -1008:Unknown error), purchase: null

### ISSUE THREAD

**Issue by WNervous** [googlesamples/android-play-billing#117]
Purchase finished: IabResult: IAB returned null purchaseData or dataSignature (response: -1008:Unknown error), purchase: null

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.
