### ISSUE TITLE
NullPointerException : IabHelper.checkSetupDone (IabHelper.java)

### ISSUE THREAD

**Issue by manpreetpatil** [googlesamples/android-play-billing#118]
I'm getting lot of users report of this error. Please help me

java.lang.NullPointerException: 
  at com.purchase.inappbillingdemo.util.IabHelper.checkSetupDone (IabHelper.java)
  or                     .dispose (IabHelper.java)
  or                     .getResponseCodeFromBundle (IabHelper.java)
  or                     .getResponseDesc (IabHelper.java)
  or                     .launchPurchaseFlow (IabHelper.java)
  or                     .launchSubscriptionPurchaseFlow (IabHelper.java)
  or                     .queryInventory (IabHelper.java)
  or                     .queryInventoryAsync (IabHelper.java)
  or                     .queryPurchases (IabHelper.java)
  or                     .querySkuDetails (IabHelper.java)
  or                     .startSetup (IabHelper.java)
  at com.purchase.inappbillingdemo.util.IabHelper.checkSetupDone (IabHelper.java)
  or                     .dispose (IabHelper.java)
  or                     .getResponseCodeFromBundle (IabHelper.java)
  or                     .getResponseDesc (IabHelper.java)
  or                     .launchPurchaseFlow (IabHelper.java)
  or                     .launchSubscriptionPurchaseFlow (IabHelper.java)
  or                     .queryInventory (IabHelper.java)
  or                     .queryInventoryAsync (IabHelper.java)
  or                     .queryPurchases (IabHelper.java)
  or                     .querySkuDetails (IabHelper.java)
  or                     .startSetup (IabHelper.java)
  at com.purchase.inappbillingdemo.util.IabHelper$2.run (IabHelper.java)
  at java.lang.Thread.run (Thread.java:818)

**Comment by RubenMH** [comment]
Hi. It happens the same to me. Have you been able to solve it?

**Comment by marcel3007** [comment]
@RubenMH You should use the new play library 

https://developer.android.com/google/play/billing/billing_library.html

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. If the problem continues, please post this question on StackOverflow. Presently we are reserving Github for questions specifically about the samples so we can better serve you.
