### ISSUE TITLE
Unable to get a purchase data and signature after completed payment successfull

### ISSUE THREAD

**Issue by talentapps** [googlesamples/android-play-billing#119]
I was use beta test account in google play. Everything was set right.but i could not get purchase data and data signature . so can any one help me?

**Comment by talentapps** [comment]
![in app purchase code](https://user-images.githubusercontent.com/35755921/35316152-0da1c29e-00f6-11e8-858e-9626b7d5304e.png)
![in app purchase code2](https://user-images.githubusercontent.com/35755921/35316153-0dde2310-00f6-11e8-9737-630433c3759b.png)
![in app purchase code3](https://user-images.githubusercontent.com/35755921/35316154-0e18c47a-00f6-11e8-8eb8-74f33368536e.png)
![in app purchase code4](https://user-images.githubusercontent.com/35755921/35316155-0e52df8e-00f6-11e8-8f02-a05370ac956a.png)
![log details for in app purchase](https://user-images.githubusercontent.com/35755921/35316156-0e8f212e-00f6-11e8-81b9-586c91ab8f92.png)

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please post this question on StackOverflow. Presently we are reserving Github for questions specifically about the samples so we can better serve you.
