### ISSUE TITLE
Is anyone from Google participating in this project anymore?

### ISSUE THREAD

**Issue by jkane001** [googlesamples/android-play-billing#12]
There are a couple pull requests and several open issues that have been sitting for quite some time, and it seems that the guy who was participating from Google's side (@PaulRashidi) isn't participating any more.

Can someone from Google help out with PRs and Issues?

Thanks!

**Comment by wjarek** [comment]
@jkane001 - I am sorry about that and will follow up on this.

**Comment by PaulRashidi** [comment]
It's a busy time of year. I accepted the main outstanding pull requests after review. Could you comment on the outstanding issues if they are blocking you?
