### ISSUE TITLE
Android Play Billing Library Repository

### ISSUE THREAD

**Issue by nullptr2this** [googlesamples/android-play-billing#120]
I would like to submit a PR against the actual library itself and not the sample applications.  I do not see the library code hosted here and my scan through AOSP did not reveal it's location there either.

Is the library open for contributions?  And if so does anyone know where to submit PRs?

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.
