### ISSUE TITLE
java.util.zip.ZipException: duplicate entry:

### ISSUE THREAD

**Issue by ManzzBaria** [googlesamples/android-play-billing#121]
I am using SDK and host app and i need to add on both aidl file SDK and host app... its working fine on debug and i am getting error while generating signed apk..

Error:Execution failed for task ':app:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/android/vending/billing/IInAppBillingService$Stub$Proxy.class

i have already tried exclude on gradle but still not works...
i have found one solution here: https://stackoverflow.com/questions/20326791/proguard-with-in-app-purchase-duplicate-zip-entry-error

but i dont know how to use it.
i have already spent too many time
Can anyone please help me for this error ?

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.
