### ISSUE TITLE
Billing cache contains outdated purchases - cancelled subscriptions are still 'owned'.

### ISSUE THREAD

**Issue by Bevor** [googlesamples/android-play-billing#126]
The` com.android.vending.billing.IInAppBillingService.getPurchases(int apiVersion, String packageName, String type, String continuationToken)` usually returns purchases that are owned. When you cancel a test subscription and the subscription period has ended, the purchase remains in cache, that means that it always returns outdated subscription which are not valid anymore. 
The implementation of IabHelper recognizes existing subscriptions, it wants to upgrade or downgrade the existing subscription. Since this subscription does not really exists except inside the cache, the user would get an error message from the built in subscription Activity: "We are unable to change your subscription plan", which is clear, because I want to change a subscription plan which does not exist anymore, since I pass the "owned" subscription to the IabHelper's 
`public void launchPurchaseFlow(Activity act, String sku, String itemType, List<String> oldSkus, int requestCode, OnIabPurchaseFinishedListener listener, String extraData)`
 method. 
This is obviously a problem of Google Play Services. You can execute 
`adb shell pm clear com.android.vending` to clean the cache, but this is no solution for end users. Is there any possibility to solve this in a suitable way? The more important question is, how long does this stay in cache?

**Comment by phrozenra** [comment]
I'm using the new Billing Library and this is still an issue even with the newer version. Cancelled / refunded purchases still show up in ones purchases list when onQueryPurchasesFinished() gets called.

There's no way for us to determine the actual status of those purchases, and from what I can gather from other sources on the internet, the cache only resets when the user's device is restarted (which might be never)

**Comment by Bevor** [comment]
Thanks for the info. The cache doesn't even reset after restart. At least this was so in my case. Ok then, I have to somehow bypass this in IabHelper, because I have all this information about purchased or not in my back-end server. This is very annoying but obviously the only safe solution.

**Comment by maxxx** [comment]
looks like same as https://github.com/googlesamples/android-play-billing/issues/122

**Comment by Bevor** [comment]
@maxxx you are right. Sorry, didn't see it.
