### ISSUE TITLE
Check if user is qualified for introductory prices?

### ISSUE THREAD

**Issue by MinaSamy** [googlesamples/android-play-billing#128]
I have a question regarding how to check if user is qualified for introductory prices when purchasing a product/subscription.

Right now `getSkuDetails()` retrieves the introductory prices regardless of the user's purchase history, so theoretically a user can purchase a subscription with an intro price, then cancels it and tries to purchase again and the APIs will not provide any information that this product has been purchased before with the introductory price.

`queryPurchases()﻿` method can tell if a product was purchased before or not, but it doesn't tell what price or whether introductory price was available when the product was purchased.

Is there any other way to validate if the user has purchased a product with an introductory price before?

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.
