### ISSUE TITLE
Ugly animation on launchBillingFlow() with black statusbar behind app's statusbar.

### ISSUE THREAD

**Issue by dementia2029** [googlesamples/android-play-billing#135]
I do not like the way how the billing popup is shown. On Android P it is a translucent activity with popup and black status bar that are moving from bottom to top. Very ugly. Pls, do not override the app's statusbar.

**Comment by Actine** [comment]
+1 this. Although I think it's not BillingClient's fault (I tried working around it, and the ProxyBillingActivity is not a culprit), but the actual Play Store purchase flow activity (which looks like a dialog but is still an activity, and uses a default platform transition or whatever) — and has to be fixed there, being beyond this client's reach.

**Comment by zeeshanaslam78** [comment]
@Actine It works. This is exactly what I was looking for. Thanks man.
I was using this only 
`<item name="android:statusBarColor">@android:color/transparent</item>`
But magic happened using with this 
`<item name="android:windowDrawsSystemBarBackgrounds">true</item>`

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.

**Comment by ashughes** [comment]
FYI, I filed a ticket: https://issuetracker.google.com/issues/153476408

**Comment by armandojimenez** [comment]
> +1 this. Although I think it's not BillingClient's fault (I tried working around it, and the ProxyBillingActivity is not a culprit), but the actual Play Store purchase flow activity (which looks like a dialog but is still an activity, and uses a default platform transition or whatever) — and has to be fixed there, being beyond this client's reach.
> 
> UPD: nope, this is actually a ProxyBillingActivity's fault. I found a workaround. You have to create a theme like this:
> 
> ```
> <style name="BillingProxy" parent="android:Theme.Translucent.NoTitleBar">
>     <item name="android:statusBarColor">@android:color/transparent</item>
>     <item name="android:navigationBarColor">@android:color/transparent</item>
>     <item name="android:windowDrawsSystemBarBackgrounds">true</item>
> </style>
> ```
> 
> and apply it to ProxyBillingActivity in your AndroidManifest.xml like this:
> 
> ```
> <activity
>         android:name="com.android.billingclient.api.ProxyBillingActivity"
>         android:theme="@style/BillingProxy"
>         tools:replace="android:theme" />
> ```
> 
> It keeps the animation but removes black bars, making the activity completely transparent.

Any one knows how to do this in Flutter? com.android.billingclient.api.ProxyBillingActivity is showing as class not found
