### ISSUE TITLE
Can not purchase from different accounts and cards in different apps.

### ISSUE THREAD

**Issue by dementia2029** [googlesamples/android-play-billing#138]
Can not purchase from different accounts and cards in different apps.
In Google Play Console all orders have status "order declined". The error on the mobile screen is "the transaction is rejected". We have tried to use different accounts, created new ecards - no luck. Even our old apps now have troubles with purchase. The error code is 7.

**Comment by dearmash** [comment]
https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponse.html#ITEM_ALREADY_OWNED

Make sure you're checking queryPurchases before trying to launch the billing flow.

https://developer.android.com/reference/com/android/billingclient/api/BillingClient#querypurchases

If you need to be able to buy something multiple times, then after you purchase it, you need to consume it.

https://developer.android.com/reference/com/android/billingclient/api/BillingClient#consumeasync

After that, it's up to you to maintain the purchase of that item.

**Comment by dementia2029** [comment]
Close the issue. The reason have been gone after several days after cancelling orders. Very weird..
