### ISSUE TITLE
MainActivity is calling queryInventoryAsync in onCreate instead of in onResume

### ISSUE THREAD

**Issue by sjvc** [googlesamples/android-play-billing#14]
Reading [official docs](http://developer.android.com/intl/es/google/play/billing/billing_promotions.html#supporting) for supporting In-app promotions, I read:

> To support promotion codes, your app should call the getPurchases() method whenever the app starts or resumes. This simplest approach is to call getPurchases() in your activity's onResume()
> 
> To listen for the PURCHASES_UPDATED intent, dynamically create a BroadcastReceiver object and register it to listen for "com.android.vending.billing.PURCHASES_UPDATED". Register the receiver in your activity's onResume()

In the code in this sample, in MainActivity, you are calling getPurchases (queryInventoryAsync), and registering the receiver in onCreate instead of in onResume. So if a promo code is used in Play Store app while the app is open, when the app resumes it won't be notified (because onCreate is not executed).

So, does this sample need to be modified in order to support in-app promotions? (apart from the [issue](https://github.com/googlesamples/android-play-billing/issues/7) that makes impossible to verify developer payload)

**Comment by netomarin** [comment]
Hi @sjvc 

I've already updated the issue #7 with details about developerPayload.
Also, our docs were updated about security and validations recommendations.

Best regards
