### ISSUE TITLE
About setAccountId

### ISSUE THREAD

**Issue by sunquan1985** [googlesamples/android-play-billing#141]
When "BillingFlowParams.Builder" is set account by method "setAccountId"，How I can get the account while receiving the purchase result or other scenes? either the client lib or server will be ok.

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.
