### ISSUE TITLE
No  purchases in onPurchasesUpdated 

### ISSUE THREAD

**Issue by zazu27** [googlesamples/android-play-billing#142]
Purchases list equals null in every payment in onPurchasesUpdated. But responseCode = BillingClient.BillingResponse.OK.
I use test subscription. So why purchases equals null?

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please post this question on StackOverflow. Presently we are reserving Github for questions specifically about the samples so we can better serve you.
