### ISSUE TITLE
Feature Request - Promo Codes OrderId

### ISSUE THREAD

**Issue by GuanacoDevs** [googlesamples/android-play-billing#145]
Is there any chance to add `orderId` to Promo Codes.
I have been using the `orderId` to verify purchases, however since currently `orderId` is empty for Promo Codes, that breaks my verification process.
If that's not possible, how can I differentiate regular purchases from Promo Codes?
#7

**Comment by dtaylorus** [comment]
This is a bug, not a feature request. Can you change the title?

Security best practices (https://developer.android.com/google/play/billing/billing_best_practices) explicitly says to verify that the `orderId` is unique.

Without this check, the same receipt can be replayed to the server over and over for infinite purchases.

This bug makes promo codes unusable without opening a huge security hole.

**Comment by GuanacoDevs** [comment]
I really don't think that changing the title will make any difference.
My workaround, not to use Promo Codes. I'm using License Testing whenever I want to give away any In App Product.

**Comment by GamelyAnthony** [comment]
Can we re-open this?
This is an on-going issue, and the workaround of using purchaseTime is fragile because, conceivably, two users could redeem a promo code at the exact same time, and thus have the same purchaseTime.

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.

**Comment by manwithsteelnerves** [comment]
Can we use OrderId+PurchaseToken as key?
