### ISSUE TITLE
How to get consumtion state

### ISSUE THREAD

**Issue by TobiasReich** [googlesamples/android-play-billing#146]
With the "old" IabHelper I was able to fetch only purchases that were not consumed yet.
Now with the billingclient 1.1 I can only fetch all previous purchases but they don't offer any information about that.
I saw I could get a rough idea about whether it's not consumed yet by trying to purchase it again but that is not an option.
What I need is a list of unconsumed items. Is that functionality removed now???

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.
