### ISSUE TITLE
In App Purchase does not update UI after a successful purchase

### ISSUE THREAD

**Issue by thangsopheap** [googlesamples/android-play-billing#150]
Today, I am implementing In App Billing into my game and I wonder why the UI was not update:

1. I want Start Game button is 'View.VISIBLE' after purchased
2. I want Buy Game button is 'View.GONE' after purchased

Test to purchase is successful but the UI is not update as what I expected. Can anybody know the problem? Below is my full code. Thank you so much.

`

    public class mygamebilling extends AppCompatActivity {
    private static final String TAG = "MyGameBilling";
    static final String SKU_PREMIUM = "android.test.purchased";
    static final int RC_REQUEST = 10001;
    IabHelper mHelper;
    private ImageButton startGame_Btn, upgradeGame_Btn;
    
    @Override
    public void onCreate(Bundle savedInstanceState) 
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.mygamebilling_gui);

	String base64EncodedPublicKey = "abc123456789";
        mHelper = new IabHelper(this, base64EncodedPublicKey);
	mHelper.startSetup(new IabHelper.OnIabSetupFinishedListener()
        {
            public void onIabSetupFinished(IabResult result)
            {
                if (!result.isSuccess())
                {
                    Log.d(TAG, "In-app Billing setup failed: " + result);
                } 
                else 
                {
                    Log.d(TAG, "In-app Billing is set up OK");
                    mHelper.enableDebugLogging(true, TAG);
                }
            }
        });
    startGame_Btn = findViewById(R.id.startgame);
    startGame_Btn.setVisibility(View.GONE);
    upgradeGame_Btn = findViewById(R.id.buygame);
    }
    
    public void upgradeGame_Btn(View arg0)
    {
        //Buy Full Version Dialog
        buyFullVersion_Dialog();
    }
    
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data)
    {
        if (!mHelper.handleActivityResult(requestCode, resultCode, data))
        {
            super.onActivityResult(requestCode, resultCode, data);
        }
        else
        {
            Log.d(TAG, "onActivityResult handled by IABUtil.");
        }
    }

    IabHelper.OnIabPurchaseFinishedListener mPurchaseFinishedListener = new IabHelper.OnIabPurchaseFinishedListener()
    {
        public void onIabPurchaseFinished(IabResult result, Purchase purchase)
        {
            if (result.isFailure())
            {
                return;
            }
            else if (purchase.getSku().equals(SKU_PREMIUM))
            {
                consumeItem();
                upgradeGame_Btn.setVisibility(View.GONE);
            }
        }
    };

    public void consumeItem()
    {
        mHelper.queryInventoryAsync(mGotInventoryListener);
    }

    IabHelper.QueryInventoryFinishedListener mGotInventoryListener = new IabHelper.QueryInventoryFinishedListener()
    {
        public void onQueryInventoryFinished(IabResult result, Inventory inventory)
        {
            if (result.isFailure())
            {
                //error
            }
            else
            {
                mHelper.consumeAsync(inventory.getPurchase(SKU_PREMIUM), mConsumeFinishedListener);
            }
        }
    };

    IabHelper.OnConsumeFinishedListener mConsumeFinishedListener = new IabHelper.OnConsumeFinishedListener()
    {
        public void onConsumeFinished(Purchase purchase, IabResult result)
        {
            if (result.isSuccess())
            {
                startGame_Btn.setVisibility(View.VISIBLE);
            }
            else 
            {
                //Error handling
            }
        }
    };
	
    @Override
    public void onDestroy()
    {
        super.onDestroy();
        if (mHelper != null) mHelper.dispose();
        mHelper = null;
    }
    }

`

**Comment by isaidamier** [comment]
If feasible for you, please take a look at the [TrivialDriveKotlin](https://github.com/googlesamples/android-play-billing/tree/master/TrivialDriveKotlin) sample. Apologies for the issues you are experiencing. Please post this question on StackOverflow. Presently we are reserving Github for questions specifically about the samples so we can better serve you.
