### ISSUE TITLE
Unable to debug when running the mobile configuration

### ISSUE THREAD

**Issue by jgriffin-isp** [googlesamples/android-play-billing#151]
When I run the instant project, I can set breakpoints in the shared-module and debug normally. When running the mobile project, with implementation project(':shared-module'), I can't hit any of the breakpoints.

Has anyone else seen this? Any workarounds?

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Presently we are reserving Github for questions specifically about the samples. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".
