### ISSUE TITLE
No OrderId in response json when using Billing library 

### ISSUE THREAD

**Issue by trungnn307** [googlesamples/android-play-billing#153]
I'm using com.android.billingclient:billing:1.1 to implement IAP. In the beginning i can even get orderId from test license which is seem wrong. Then suddenly i cant get  any orderId in response code even i use the real visa card to pay. So it breaks the server verification process. 
   Then i rollback my code to use aidl and everything is fine. The orderId is in the response.  
Sample response with billing library 
`08-18 13:14:57.390 7223-7223/? E/onConsumeFinished: {"productId":"ttsk.usd.001","purchaseToken":"maogblhngoeihmolfjchakdp.AO-J1Ox40gcHpDlrAeDmreagktDEQ6R1MO5HkMzsg8svIWalFb5lox8qCafbzZp3KsZWahrQ8WpS2drIb8x1wNQuK6lRU3JxrsKieaMNoL8YVZ47YtIN7F93c4Jy2FfMlommws2ebUAu","purchaseTime":1534572891188,"developerPayload":null}`

Response using AIDL 

`08-18 15:15:27.666 10322-10322/? E/onConsumeFinished: {"orderId":"GPA.3346-5505-8191-98269","packageName":"com.gamemobile.ttskfull","productId":"ttsk.usd.001","purchaseTime":1534580120781,"purchaseState":0,"purchaseToken":"oonkjbgmclfcleaiblbijmdh.AO-J1OyBvm_NTdkocMHFTVsw8tiJRksS6MAR0MXO_xhwUDJHSQShf_yoIgMOjxivn8cYbYUDDWj_-Ca0XIWnREXdH27138Xrzf-Pvt3TdIYHAQVd9XMu37sTUbistH9apM1KVsm6E7nN"}`

![image](https://user-images.githubusercontent.com/1224582/44297427-70566000-a2fb-11e8-901a-823e9c8c725f.png)

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Presently we are reserving Github for questions specifically about the samples. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".
