### ISSUE TITLE
Lack of synchronous methods in Billing

### ISSUE THREAD

**Issue by xzhorikx** [googlesamples/android-play-billing#154]
Current implementation of [BillingClient](https://developer.android.com/reference/com/android/billingclient/api/BillingClient) states that 

> [...] It provides **synchronous (blocking)** and asynchronous (non-blocking) methods for many common in-app billing operations. [...]

However, currently there are no synchronous methods for consuming or queering SKU items which obstructs the flow of the use cases where items must be displayed or consumed. Please add synchronous versions of following methods:

[BillingService.consumeAsync(String purchaseToken, ConsumeResponseListener listener)](https://developer.android.com/reference/com/android/billingclient/api/BillingClient#consumeAsync(java.lang.String,%20com.android.billingclient.api.ConsumeResponseListener))
[BillingService.querySkuDetailsAsync (SkuDetailsParams params, SkuDetailsResponseListener listener)](https://developer.android.com/reference/com/android/billingclient/api/BillingClient#querySkuDetailsAsync(com.android.billingclient.api.SkuDetailsParams,%20com.android.billingclient.api.SkuDetailsResponseListener))

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Presently we are reserving Github for questions specifically about the samples. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".
