### ISSUE TITLE
hostnameverifier issue in inappbilling

### ISSUE THREAD

**Issue by tapas4git** [googlesamples/android-play-billing#155]
Hi,

I am not able to publish my app in play store. I got hostnameverifier issue in my old code which implements InApp Billing facility. I have no idea where and what to change in my old code. Kindly guide me on this.

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Presently we are reserving Github for questions specifically about the samples. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".
