### ISSUE TITLE
Purchase the same item twice but without consume the first one ? 

### ISSUE THREAD

**Issue by LNeway** [googlesamples/android-play-billing#161]
One of our user Purchase the same item twice but without consume the first one , and from the log the onIabPurchaseFinished method not called correctly.

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Presently we are reserving Github for questions specifically about the samples. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".
