### ISSUE TITLE
所请求的类型不支持 Billing API 版本D/BillingManager: Setup finished. Response code: 3

### ISSUE THREAD

**Issue by guanshichao** [googlesamples/android-play-billing#169]
什么导致了：所请求的类型不支持 Billing API 版本？
文档上说：应用内购买结算版本 3 是最新版本，依然具有非常广泛的兼容性，可用于各种 Android 设备。 运行 Android 2.2（API 级别 8）或更高版本且安装了最新版本的 Google Play 应用的设备（绝大多数有效设备）都支持使用应用内购买结算版本 3
我的三个设备都满足，为什么都是D/BillingManager: Setup finished. Response code: 3
？？？

**Comment by pfmaggi** [comment]
Can you please add more information?

**Comment by audientlin** [comment]
```java
billingClient.startConnection(object : BillingClientStateListener {
            override fun onBillingSetupFinished(@BillingClient.BillingResponse billingResponseCode: Int) {
                LogUtils.d(TAG, "onBillingSetupFinished")
...
```
billingResponseCode is 3

**Comment by guanshichao** [comment]
你好，这个问题我解决了。后来发现是需要上传到Google Play Console 之后，才可以测试购买。
只是这个错误码很难联想到是这个问题。
