### ISSUE TITLE
billingClient.querySkuDetailsAsync doesn't return updated prices

### ISSUE THREAD

**Issue by LluisFelip** [googlesamples/android-play-billing#178]
Steps to reproduce:

1. Set product price in Google Play Console to 10 €
2. With a properly initialised billingClient connection we call billingClient.querySkuDetailsAsync to retrieve the skuDetails.
3. We receive skuDetails with a price of 10 €
4. Set product price in Google Play Console to 20 €
5. Start the app again and after step 2:

**Expected:** skuDetails price should be 20 €

**Actual:** skuDetails price is 10 € but when we call billingClient.launchBillingFlow the price shown there is 20 €

We think querySkuDetailsAsync is an asynchronous call to network to retrieve the latest info but it seems its returning some cache info.

Thanks in advance!

**Comment by blackCmd** [comment]
Oh i got a same issue.
"
We think querySkuDetailsAsync is an asynchronous call to network to retrieve the latest info but it seems its returning some cache info.
"

**Comment by chocolatesoup** [comment]
See the discussion here:
https://github.com/googlesamples/android-play-billing/issues/122
It seems it is impossible to clear the billing cache on a user's device...

**Comment by isaidamier** [comment]
Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library"
