### ISSUE TITLE
queryPurchases() and queryPurchaseHistoryAsync() doesn't work well if payment is interrupted

### ISSUE THREAD

**Issue by huster001** [googlesamples/android-play-billing#179]
It's an issue that can be reproduced. 

1, launch a payment flow 
2, tap to pay
3, disconnect  network of the device within 1 second,  you need to be pretty fast!
4, you will get an error dialog
5, reconnect your network
6, try to purchase the same shop item
7, tap to payment
8, you get an error saying "you have already owned this item"

If you step to 8,  you may expect to call queryPurchases() or queryPurchaseHistoryAsync() to get the unverified purchased item, verify it and then call consumeAsync() to complete the payment transcation.

The fact is that I could not get the unverified purchased item from both APIs. the only way to fix it is to clear the cache and data of the Google Play Store app, and then both API worked well again, the billing process could continue.

Below is a video that shows how to reproduce it.
https://youtu.be/uM64Lq5FZUM

**Comment by isaidamier** [comment]
Thanks for reporting this issue. We will look into it internally.

**Comment by isaidamier** [comment]
Hi, might you be able to share the logcat with us? Thanks!

**Comment by isaidamier** [comment]
Please report this isPlease file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library"sue at https://issuetracker.google.com
