### ISSUE TITLE
Please review for basic professionalism

### ISSUE THREAD

**Issue by rharter** [googlesamples/android-play-billing#186]
I'd appreciate if the code in this official sample could be reviewed to maintain a high quality of professionalism that avoids sounding condescending to the developers reading the sample code.  My discussions with some other developers, specifically in references to the Kotlin sample's [BillingRepository](https://github.com/googlesamples/android-play-billing/blob/master/TrivialDriveKotlin/app/src/main/java/com/kotlin/trivialdrive/billingrepo/BillingRepository.kt) class is what spurred this issue.

It's particularly infuriating since this is a 1000 line class with several unimplemented methods for which you're also supposed to provide your own "secure server" implementation, according to the author to provide purchases from other platforms or to prevent fraud, but that you can't actually provide the required functionality of subscriptions without (he does point out that he doesn't support subscriptions here).  This, in my opinion, highlights that this is clearly an inadequate API (Play Billing) and a real pain point for users. Since I came to these samples to deal with those pain points of this lacking API, I'd rather not be confronted with statements like "This is not complicated" and "that's the whole point of a sample".

Examples of unprofessional or condescending comments in code:

* [Calls should not be made to the secure server too often -- it's co$tly](https://github.com/googlesamples/android-play-billing/blob/master/TrivialDriveKotlin/app/src/main/java/com/kotlin/trivialdrive/billingrepo/BillingRepository.kt#L469)
* [While the architecture presented here and 95% of the code is highly reusable **(that's the whole point of a sample)** ...](https://github.com/googlesamples/android-play-billing/blob/master/TrivialDriveKotlin/app/src/main/java/com/kotlin/trivialdrive/billingrepo/BillingRepository.kt#L171-L172)
* [This is not complicated](https://github.com/googlesamples/android-play-billing/blob/master/TrivialDriveKotlin/app/src/main/java/com/kotlin/trivialdrive/billingrepo/BillingRepository.kt#L559-L561)

**Comment by lateplate** [comment]
100% agree -- had a hard time believing I was reading an official Google sample. The billing API is already very difficult to work with, and the attempts at humor (?) don't make it any easier. It all just adds unnecessary noise and makes it more difficult to understand.

**Comment by rspq** [comment]
Seems a weird thing to get annoyed about. I seldom do Android dev these days but that 1,000 line class seems unusually well commented to me. Yes Billing has a needlessly complex API but that's par for the course with Android.

**Comment by tjohns** [comment]
Thanks for the feedback.

I lead the team in Android Developer Relations that's responsible for these samples. We'll be taking a look at this code and associated documentation to identify areas for improvement.

**Comment by berkayturanci** [comment]
> Thanks for the feedback.
> 
> I lead the team in Android Developer Relations that's responsible for these samples. We'll be taking a look at this code and associated documentation to identify areas for improvement.

Dear @tjohns, 

Thanks for the response on this issue. We would be very happy if your team can also check out the rest of the issues like; https://github.com/googlesamples/android-play-billing/issues/180. 

Thanks!

**Comment by tjohns** [comment]
Just wanted to let folks know that this is still in progress, and we're still doing an internal review of this sample. Thanks for your patience.

We'll also be doing a review of all the open issues here over the next few weeks.

**Comment by TheRealAgentK** [comment]
Is there any update on how your review of the samples, documentation as well as the open issues here is going, @tjohns?

**Comment by TheRealAgentK** [comment]
Ping!

**Comment by TheRealAgentK** [comment]
Why the Thumbs Down, @LouisCAD? Is it not ok to ask for an update?

**Comment by miquelbeltran** [comment]
While still a minor issue compared to what @rharter reported, these also not look as the expected standard of official documentation:

- Double exclamation marks in "Notice just how small and simple this BillingViewModel is!!"

https://github.com/googlesamples/android-play-billing/blob/master/TrivialDriveKotlin/app/src/main/java/com/kotlin/trivialdrive/viewmodels/BillingViewModel.kt#L35

- Using "free from [..] tentacles!!" and the double exclamation marks, instead of saying something like "The rest of your app no longer depend on the [BillingClient]."

https://github.com/googlesamples/android-play-billing/blob/master/TrivialDriveKotlin/app/src/main/java/com/kotlin/trivialdrive/viewmodels/BillingViewModel.kt#L39

I haven't finished looking at the new Kotlin sample, it looks very promising and thanks for updating it. I will report back any other examples like this one.

**Comment by LouisCAD** [comment]
@TheRealAgentK comments like "Ping!" or "Are we there yet?", or, again, "Are we there yet?" needlessly notify everyone that subscribed to this issue. It's like asking everyone in a hospital if an operation is done. It's poorly targeted and you disturb many people for no value. The doctor would have come to you eventually when done anyway.

Our "doctor" already told us [the last status here](https://github.com/googlesamples/android-play-billing/issues/186#issuecomment-478170108), and asking repeatedly will annoy people more than speeding things up. Also, if you want a good resolution, you probably don't want to speed too much as you'd risk overlooking mistakes or problems that deserve to be addressed.

**Comment by TheRealAgentK** [comment]
@LouisCAD I frankly disagree in this case. 

The state of some of the examples in the project, the lack of responses and effectively radio silence from Google to the vast majority of tickets raised here over the last 2 yrs has been notoriously sub-optimal.

It's now 7.5 weeks ago that the original concerns were raised. 6.5 weeks ago we were told that: 

"this is still in progress, and we're still doing an internal review of this sample. Thanks for your patience. We'll also be doing a review of all the open issues here over the next few weeks."

1. "*still* in progress" implies that at the time this was already being worked on.
2. "next few weeks" implies 3, maybe 4 - or worst case 5 weeks.

As you're suggesting I'm trying to speed things up - that's untrue. I'm well aware that you can't speed things up this way.

What I'm *expecting* though is that this ticket is being kept up to date with some ongoing comments and progress from the people in charge, that's all - and I don't think that's asking for too much.

**Comment by LouisCAD** [comment]
@TheRealAgentK Alright, then next time, please comment with something more explicit like:
> Hi, last update was X weeks ago and we would like to know if that is still progressing, so we can take a decision on whether to rely on this coming some time (hopefully sooner than later this year), or not.

I think it's more likely to get you an accurate response from the assignees.

**Comment by isaidamier** [comment]
Thanks for the feedback. We have revised the long-form documentations.

**Comment by LouisCAD** [comment]
It seems a lot has changed docs-wise, including a major upgrade of the library from 1.2 to 2.0.

The [README "CHANGELOG"](https://github.com/googlesamples/android-play-billing/tree/9e7e373ae2414af9d5b170e000a2ba9deb911944#changelog) has not been updated yet though.

Could be worth a blog post to cover the changes and improvements, in addition to updating the README with changes, or adding a CHANGELOG.md file in the repo.
