### ISSUE TITLE
can not correct response code after calling consumeAsync()

### ISSUE THREAD

**Issue by GeorgeCCC** [googlesamples/android-play-billing#193]
The purchase with test account succeed, but the item cannot be consumed.
Always get response code "6" in BillingResult.

version: 2.0.0.

**Comment by tinder-yisongwu** [comment]
I could see the same issue on my testing case. Get a response code Error "6" on 2.0.0. 
The debug error message is null.

**Comment by wheelergames** [comment]
I get exactly the same. Error = 6 & empty debug message.

**Comment by pencoba** [comment]
I also get the same error "6" and empty debug message when calling consumeAsync()

I'm using version 2.0.0

Please help

**Comment by pencoba** [comment]
> 
> 
> The purchase with test account succeed, but the item cannot be consumed.
> Always get response code "6" in BillingResult.
> 
> version: 2.0.0.

In my case, when I include .setDeveloperPayload(/* payload */) in ConsumeParams I always get response code "6".

When I remove it  the purchase can be consumed ( response code "0" or OK). Like in this code:

`ConsumeParams consumeParams =
    ConsumeParams.newBuilder()
        .setPurchaseToken(/* token */)
        .build();                 
`

**Comment by GeorgeCCC** [comment]
> > The purchase with test account succeed, but the item cannot be consumed.
> > Always get response code "6" in BillingResult.
> > version: 2.0.0.
> 
> In my case, when I include .setDeveloperPayload(/* payload */) in ConsumeParams I always get response code "6".
> 
> When I remove it the purchase can be consumed ( response code "0" or OK). Like in this code:
> 
> `ConsumeParams consumeParams = ConsumeParams.newBuilder() .setPurchaseToken(/* token */) .build(); `
> 
> note: I also don't set developer payload on acknowledgePurchase()
It really works for my case.
And It looks like "setAccountId()" won't be gotten in Purchase data from queryPurchases() in this [link](https://stackoverflow.com/a/49521538/1244440)

**Comment by cartland** [comment]
Thanks for reporting this issue. Some error messages are still being rolled out through Google Play infrastructure, so you should start to see the error messages this week.

**Comment by fed-xie** [comment]
> 
> 
> > The purchase with test account succeed, but the item cannot be consumed.
> > Always get response code "6" in BillingResult.
> > version: 2.0.0.
> 
> In my case, when I include .setDeveloperPayload(/* payload */) in ConsumeParams I always get response code "6".
> 
> When I remove it the purchase can be consumed ( response code "0" or OK). Like in this code:
> 
> `ConsumeParams consumeParams = ConsumeParams.newBuilder() .setPurchaseToken(/* token */) .build(); `
> 
> note: I also don't set developer payload on acknowledgePurchase()

That's it!
When I view log with no filter, there is a log shows a 400 HTTP code responsed from Google's server.

**Comment by isaidamier** [comment]
This issue seems to have been fixed in a later roll-out. Please re-open if you upgraded to the latest library and still see the same issue.
