### ISSUE TITLE
Acknowledging already acknowledged purchases

### ISSUE THREAD

**Issue by mihirjoshi21** [googlesamples/android-play-billing#197]
So I already acknowledged a purchase.  But when I am passing the same purchase token again it is giving me Error code 6 - internal error. Instead, how can I get a message and code that tells me that the purchase is already acknowledged?

```
val params = AcknowledgePurchaseParams.newBuilder().setPurchaseToken(purchase
                    .purchaseToken).build()
playStoreBillingClient.acknowledgePurchase(params)
```

**Comment by stephanedupont** [comment]
You're not supposed to do that

See here: https://developer.android.com/google/play/billing/billing_library_releases_notes.html

> The Purchase object now includes an isAcknowledged() method that indicates whether a purchase has been acknowledged. In addition, the server-side API now includes acknowledgement boolean values for Product.purchases.get() and Product.subscriptions.get(). Before acknowledging a purchase, be sure to use these methods to determine if the purchase has already been acknowledged.

**Comment by mihirjoshi21** [comment]
Actually, I resolved it. The purchase object has a parameter `isAcknowledged`.
