### ISSUE TITLE
Clarification needed: must old purchases be acknowledged?

### ISSUE THREAD

**Issue by stephanedupont** [googlesamples/android-play-billing#198]
For in-app purchases that are not consumables (one-time purchase that unlocks premium features for example), how does this work for purchases made before Google introduced acknowledgements and before the app used Play Billing Library v2.0?

The docs are not clear about this, maybe add something about this in the documentation?

**Comment by pencoba** [comment]
Yes the documentation is not clear, lot of things still confusing.

But I've tried an experiment. First I bought an IAP using AIDL (without acknowledgement) then using Play Billing 2.0.0 I checked if it's acknowledged, the result is it is acknowledged.

**Comment by stephanedupont** [comment]
Thank you @pencoba, that's a nice test!

If someone from Google could confirm this and have it put somewhere in the documentation that would be awesome.

**Comment by c6collin** [comment]
Purchases using AIDL directly or a billing library < 2.0.0 will not need to be acknowledged by your application. When you query these purchases via our server APIs or through billing library 2.0.0 they will be marked as acknowledged. I will work on clarifying this in our documentation.

**Comment by stephanedupont** [comment]
Thank you for the confirmation @c6collin!

**Comment by stephanedupont** [comment]
@c6collin ... what about the case where we have to downgrade the library to 1.2.2 because of this issue? https://issuetracker.google.com/issues/135272926

**Comment by isaidamier** [comment]
Closing as all related issues have been resolved. Please reopen with more details if still experiencing this and related issues. https://issuetracker.google.com/issues/135272926 has been fixed in 2.0.3

**Comment by irfanadil** [comment]
I read this google official link 

If you do not acknowledge a purchase within three days, the user automatically receives a refund, and Google Play revokes the purchase.
Acknowledgement is not required when using a version of the Google Play Billing Library prior to 2.0.

So will this library be of any use if there is no way of acknowledgement? I am learning.
