### ISSUE TITLE
How to test pending purchase?

### ISSUE THREAD

**Issue by theBradfo** [googlesamples/android-play-billing#199]
I've just updated my app to use the latest play-billing billing (2.0) release, which forces you to support pending transactions or the libraries initialization fails fast.  In the release notes for this library regarding pending transactions, i see:
> Pending transactions can be tested using license testers. In addition to two test credit cards, license testers have access to two new test instruments for delayed forms of payment which automatically complete or cancel after a couple of minutes.

However at runtime, in the Google Play bottom sheet for a valid license tester there's no option for the pending transaction, so how do we test this out?  Is this feature not yet fully implemented in google play?  

I'm a bit concerned about integrating this library into my app, which relies heavily on in-app purchasing and subscription products, and being unable to test this new feature in Google Play prior to a production rollout.  Any insight or help on how to test this would be greatly appreciated!

**Comment by stephanedupont** [comment]
Yes there is. It is labelled "slow credit card" or something like that.

**Comment by theBradfo** [comment]
@stephanedupont Is this restricted by geography/region or some other setting in the play console?  I'm based in the US and do not see this for my valid license testers, I only see two options: "Test card, always approves" and "Test card, always declines" as I previously did prior to the update to play-billing 2.0.

**Comment by stephanedupont** [comment]
No idea. I answered because as it happened I just tested this a few days ago. And it worked well and as expected. But I was surprised with the label "slow card" at first.

**Comment by theBradfo** [comment]
Hmm, my thought is that it's geo-restricted, at least right now, since in the launch announcement they said it was available only in Mexico and Japan and my app is not available in those regions.  

Some confirmation from the google devs would be amazing though!

**Comment by CapnSpellcheck** [comment]
Just curious, for the delayed payment method testing, do they give any URL you can invoke in a browser that will trigger the completion? Or you just have to wait and check?

**Comment by isaidamier** [comment]
Are you still experiencing this issue? Even in the U.S. you should see four options:

- Slow test card, approves after a few minutes
- Test card, always approves
- Test card, always declines
- Slow test card, declines after a few minutes

**Comment by theBradfo** [comment]
Nope they started showing up eventually, i think maybe my version of google play services on the device was out-dated?  Whatever the case, they are working now.

**Comment by ubuntudroid** [comment]
@isaidamier I'm in Germany and I used to be able to see this, but for some reason not anymore (same goes for my colleagues). Anything we can do to force this showing up? It's quite essential that we are able to test pending purchases as we have many users in countries where pending purchases are supported.

**Comment by RUSSCITY** [comment]
@ubuntudroid same problem by me. @isaidamier any suggestions on how can we test it in Germany?

**Comment by rabiefizazi** [comment]
I'm also having the same problem. I only see "Test card, always approves" and "Test card, always declines". Is there any solution to this?

**Comment by viltit** [comment]
Same problem here in Switzerland. This is a real problem since I have no idea **at al**l if my implementation is working.

**Comment by m3toh** [comment]
I face the Same problem is there any other solution, i tryd to change the account but it didn't solves the problem

**Comment by m3toh** [comment]
@viltit did you solved the problem ?

**Comment by m3toh** [comment]
@rabiefizazi did you found any solution?

**Comment by ChuckWalters** [comment]
I only see "Test card, always approves" and "Test card, always declines".

**Comment by vegaro** [comment]
Slow cards don't work with subscriptions, only with in-app products.

**Comment by ebhsgit** [comment]
@vegaro 
Never knew that `Slow test cards` don't work with subscriptions.

Do you have link to official source for that statement?

**Comment by dev-cold** [comment]
@ebhsgit You can see it [here](https://developer.android.com/google/play/billing/integrate#pending).

There is a note right below the title:
> Additional forms of payment are not available for subscriptions purchases.

And all the following documentation describes the data only for one-time purchases.

So it looks like it's not just the pending method isn't available for test payments. But pending payments aren't available for subscriptions at all.

**Comment by ebhsgit** [comment]
@dev-cold Thanks for link

**Comment by vuthaiduy1990** [comment]
Until now 2023, I still cannot found any solution for this issue.

**Comment by tinder-wenbinchen** [comment]
seeing the same problem. anyone figures out a way out?
