### ISSUE TITLE
Google Play Developer API upgrade to v3

### ISSUE THREAD

**Issue by ghataa** [googlesamples/android-play-billing#200]
Could you please upgrade the Classy Taxi sample according to the upcoming changes in the Google Play Developer API?

https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

**Comment by cartland** [comment]
Thanks for reporting this issue. I am not aware of any breaking changes between V2 and V3, so this might just be a change to the number.

This is where the version number is specified in Classy Taxi.

https://github.com/googlesamples/android-play-billing/blob/180077a516d79e465435a4917d06b054999f82c0/ClassyTaxi/firebase/server/src/play-billing/PlayBilling.ts#L69-L72

**Comment by ghataa** [comment]
@cartland I see, thanks!
