### ISSUE TITLE
TrivialDriveKotlin: BillingClient: getSkuDetails() failed. Response code: 5

### ISSUE THREAD

**Issue by vitovalov** [googlesamples/android-play-billing#201]
Strange issue specific to Nexus 6P.
The same apk works fine on Xiaomi and Nexus 5, also on emulators. 
But on Nexus 6P I see this log:
```
D/BillingRepository: startDataSourceConnections
D/BillingRepository: connectToPlayBillingService
D/BillingRepository: onBillingSetupFinished successfully
******W/BillingClient: getSkuDetails() failed. Response code: 5******
D/BillingRepository: queryPurchasesAsync INAPP results: 0
D/BillingRepository: queryPurchasesAsync SUBS results: 0
D/BillingRepository: processPurchases called
D/BillingRepository: processPurchases newBatch content []
D/BillingRepository: processPurchases consumables content []
D/BillingRepository: processPurchases non-consumables content []
D/BillingRepository: processPurchases purchases in the local db 0
```

**Comment by vitovalov** [comment]
I've checked and a previous version of the same app, with old BillingClient ~TrivialDrive v1, works fine. 
Also other apps' inapps works fine. 
It's only the current implementation that fails.
Checked play services and play store are up to date.

**Comment by arsenioo** [comment]
Having the same issue with new Billing Library 2.0.0 or 2.0.1. In my case, the same binary works on Pixel XL API 29 and does not work on Nexus 10 API 22 and below.

**Comment by arsenioo** [comment]
Maybe the answer is here: https://stackoverflow.com/questions/17128537/in-app-billing-v3-billing-response-result-developer-error

In your case Nexus 6P may use your developer account so you get this error.

**Comment by vitovalov** [comment]
https://issuetracker.google.com/issues/135272926

**Comment by b0rski** [comment]
Exactly same for me. So which version of the billing client are you guys using now?

**Comment by arsenioo** [comment]
> Exactly same for me, maybe except for Java and not Kotlin. And this occurs while I am testing static responses for SKU like "android.test.purchased". So which version of the billing client are you guys using now?

I can confirm that this issue disappeared for me with the same binary on the same device right after I changed the test account for the purchases from the developer to another one. This issue appeared after switching the Billing library from 1.x to 2.0.0 or 2.0.1

**Comment by arsenioo** [comment]
> https://issuetracker.google.com/issues/135272926

Thanks, I will comment there too

**Comment by stephanedupont** [comment]
Same for me, was working fine before, but updating to 2.0.X has bring this error.

**Comment by isaidamier** [comment]
This issue has been fixed: https://issuetracker.google.com/issues/135272926
