### ISSUE TITLE
How to consume or acknowledge a purchase with a slow testing card right after the purchase was made?

### ISSUE THREAD

**Issue by leventepal** [googlesamples/android-play-billing#203]
**Version**: 2.0.1

Initiate the purchase:
```
val params = BillingFlowParams
                        .newBuilder()
                        .setSkuDetails(skuDetial)
                        .build()

billingClient.launchBillingFlow(activity, params)
```

After checking the billing result (OK) and if the service is still connected, I initiate a consume:

```
val consumeParams = ConsumeParams
                    .newBuilder()
                    .setPurchaseToken(purchase.purchaseToken)
                    .build()

billingClient.consumeAsync(consumeParams, this)
```

In the consume listener callback, I get the following error:

```
override fun onConsumeResponse(billingResult: BillingResult?, purchaseToken: String?) {
   // response code: DEVELOPER_ERROR = 5
   // debug message: Purchase illegal state: PENDING
}
```

After exactly 5 minutes, the "`onPurchasesUpdated()`" is getting called (as expected with a testing account), but **how am I supposed to deal with pending transactions**?

I can't let the user to wait 5 minutes with a progress dialog/view while Google validates the purchase. This should be instantaneous. Like in a real life. I go to shopping, I pay with money the cashier then I receive my product/service. 

Another thing is: should I migrate the billing client into an Android `Service`? Because, currently the Billing Client library is bound to an `Activity` and a `ViewModel`. Once the `Activity` is destroyed, the Billing Client library won't receive any updates from Google via the "`onPurchasesUpdated()`".

**Comment by Wensibob** [comment]
Hey,have you solved this question?

**Comment by algrid** [comment]
That's an interesting question - what is the recommended way to deal with slow cards in general?
