### ISSUE TITLE
the latest version is not 2.0.1?

### ISSUE THREAD

**Issue by BingzhaoChen** [googlesamples/android-play-billing#208]
what is the version 2.0.1? v3?

**Comment by BingzhaoChen** [comment]
https://developer.android.com/google/play/billing/billing_library_releases_notes

**Comment by tjohns** [comment]
The latest version of the Android client library is v2.0.2. (See the release notes at ttps://developer.android.com/google/play/billing/billing_library_releases_notes.)

The latest version of the Play Developer API for server-side integrations is v3.

**Comment by pmrajani** [comment]
@tjohns Can we have any sample example for v2.0.2 with use of consumable item. @BingzhaoChen
