### ISSUE TITLE
Why not add Java code?

### ISSUE THREAD

**Issue by ridone6** [googlesamples/android-play-billing#210]
I only know Java. I can't read the samples because I don't know Kotlin. Why not add Java code ?
Why am I being forced to learn a language I don't want to learn ? Congratulations Google

**Comment by FuckMicr0soft** [comment]
Google has some balls, you have to give it to them. They take 30% of every transaction, provide outdated non functioning docs and examples and the ones they publish are in a program language literally NO ONE uses. Kudos!

**Comment by tjohns** [comment]
The TrivialDrive sample is already available in Java. Additionally, all of the documentation for Play Billing is available in both Java and Kotlin format.

**Comment by ridone6** [comment]
of course a java code that was last updated 3 years ago.I hope your monopoly in the market will end one day.
