### ISSUE TITLE
Can't Build. Program type already present: com.example.billingsample.BuildConfig

### ISSUE THREAD

**Issue by udoy-touhid** [googlesamples/android-play-billing#211]
Just Cloned the project. Updated `APP_ID` in gradle. Added key properties.
Can't build the product. With multiple warnings and one error.

```
AGPBI: {"kind":"error","text":"Program type already present: com.example.billingsample.BuildConfig","sources":[{}],"tool":"D8"}
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':mobile:transformClassesAndResourcesWithR8ForDebug'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

```

**Comment by mariuspena** [comment]
@udoy-touhid did you find a fix ?

**Comment by udoy-touhid** [comment]
I have changed the package name in AndroidManifest.xml to some random name. It works then.

`package="com.example.billingsample"` to `package="com.example.billingsample2"`

**Comment by mariuspena** [comment]
oh yes. that was silly. it was also written on the read.me :)

**Comment by udoy-touhid** [comment]
Really? where? Readme wrote to update APP_ID in build.gradle, but not in manifest
