### ISSUE TITLE
querySkuDetailsAsync occasionally returns BillingResponseCode.ERROR

### ISSUE THREAD

**Issue by Redbu11dev** [googlesamples/android-play-billing#217]
Hello. I am using billing library 2.0.3 and it works fine for the most part, but for some users for the reasons unknown, `querySkuDetailsAsync()` method occasionally fails with `BillingResponseCode.ERROR` (6) error code...

Does anyone know anything about it? The reason of this error is not explained anywhere, other than it is a "Fatal error during the API action", can anyone maybe tell why it might be happening?

Could the users simply cheat? e.g. use a cracked google play store/other software that is messing with the purchases? Because I am not getting this error on any of the devices that I have, no matter what I do.

**Comment by isaidamier** [comment]
We are tracking this issue at https://issuetracker.google.com/issues/139631105
