### ISSUE TITLE
IABHelper `queryInventoryAsync` sets `mDisposed` to false before checking it.

### ISSUE THREAD

**Issue by tbook** [googlesamples/android-play-billing#22]
If `disposeWhenFinished()` has set `mDisposeAfterAsync` to true, `queryInventoryAsync` will set `mDisposed` to false when it calls `flagEndAsync`.  It will then test `mDisposed` and not post the callback.

This could be fixed by not calling `flagEndAsync` until after the callback has been called, or caching the value of `mDisposed` from before the call to `flagEndAsync`.

**Comment by tbook** [comment]
See PR #23

**Comment by netomarin** [comment]
Fixed by disposal in the onDestroy method.
Thanks.
