### ISSUE TITLE
How do I distinguish between in-app purchases and promotion purchases?

### ISSUE THREAD

**Issue by kdang-individual** [googlesamples/android-play-billing#226]
I proceeded with inapp purchases and promotional purchases.

When querying Purchase object by calling queryPurchases () after purchase, inapp purchase is passed "orderId" and promotion purchase is not passed "orderId".

Can I differentiate between them based on the presence of "OrderId"?

Does the Purchase object obtained by calling queryPurchases () provide an alternative to distinguish between inapp purchases and promotion purchases?

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please post this question on StackOverflow and we’ll help answer it there. Presently we are reserving Github for questions specifically about the samples so we can better serve you.
