### ISSUE TITLE
The purchaseType cannot be resolved in the client API. Do you have any plans to provide?

### ISSUE THREAD

**Issue by kdang-individual** [googlesamples/android-play-billing#231]
In the server api, you can find the purchaseType of the purchase.
You can't check it in the client api. Do you have plans to provide this?

https://developer.android.com/reference/com/android/billingclient/api/Purchase.html
https://developers.google.com/android-publisher/api-ref/purchases/products

**Comment by isaidamier** [comment]
Generally we do not comment on future plans. Do you have a specific use case you would like help solving? If so, there are two ways to proceed: if it's a general question, you should post on StackOverflow. 

If it's a feature request please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library". Presently we are reserving Github for questions specifically about the samples so we can better serve you.
