### ISSUE TITLE
Updating google play billing library to 2.0.3 is not working, purchase is always refunded

### ISSUE THREAD

**Issue by Raspberry83** [googlesamples/android-play-billing#237]
I had a working implementation of in-app billing, using the billing client 1.0.2 library (learning from the example TrivialDrive_v2) and everything worked fine. I have a simple premium upgrade, without subscriptions.

Now I tried to upgrade to 2.0.3, I made all the necessary changes to my code (using official documentation, release notes, and StackOverflow) and it doesn't work. I know I must acknowledge all purchases within three days. Failure to correctly acknowledge purchases will result in beeing refunded. And that's what I did.

The entire purchase workflow looks okay, the behavior is like before the library is updated. But in the end my purchase is always refunded after 5 minutes (using a trial account, so it's 5 minutes instead of 3 days).

this is inside handlePurchase(purchase) - called by onPurchasesUpdated:

     `if (purchase.getPurchaseState() == Purchase.PurchaseState.PURCHASED) {
              if (!purchase.isAcknowledged()) {

                AcknowledgePurchaseParams acknowledgePurchaseParams = AcknowledgePurchaseParams.newBuilder().setPurchaseToken(purchase.getPurchaseToken()).build();

                AcknowledgePurchaseResponseListener acknowledgePurchaseResponseListener = new AcknowledgePurchaseResponseListener() {
                    @Override
                    public void onAcknowledgePurchaseResponse(BillingResult billingResult) { 
                        Toast.makeText(getContext(), "Purchase acknowledged", Toast.LENGTH_LONG);
                    }
                };

                mBillingClient.acknowledgePurchase(acknowledgePurchaseParams, acknowledgePurchaseResponseListener);
            }
    }`

Thats what I can see in debug mode: in onAcknowledgePurchaseResponse my billingResult response code is 5 (developer error), the debug message is empty (""). And I have no idea what's wrong. I've spent many days on finding the issue, but could't get it.

The TrivialDrive sample hasn't been updated to v2 yet. In Google Play Billing Library release notes I can see, that there was a bug with returning code DEVELOPER_ERROR instead of returning a successful result, but I already use the newest version.

Thank you very much for your help, 

Raspberry

**Comment by MeisterTea** [comment]
Exactly the same here, what are we supposed to do with the v3 behind forced to us from December 1... 😔

**Comment by isaidamier** [comment]
Have you verified that you are using a test account different from your own? i.e. other than the developer's email account? Also can you verify whether you are getting the same error when you call "getSkuDetails()"? This sounds a bit similar to https://issuetracker.google.com/issues/135272926

We apologize for the issues you are experiencing. If your issue is not resolved by this advice, please  post this question on StackOverflow with tag google-play-billing and we’ll help answer it there. Currently we are reserving GitHub for questions specifically about the samples.

**Comment by Raspberry83** [comment]
Hello isaidamier, thank you for your answer. Yes, my test account is different from my developers email account. It was working great using the billing client library 1.0.2, I tested it right before upgrading to 2.0.3 (with the same test account) and everything worked.

I am going to check if getSkuDetails() gets the same error and I will write it in a new comment.

I already posted my question on stackoverflow some days ago: https://stackoverflow.com/questions/58215335/updating-google-play-billing-library-to-version-2-is-not-working-purchase-is-al

Thank you, Raspberry

**Comment by Raspberry83** [comment]
Hallo isaidamier, could you already take a look at my stackoverflow question? I really have no idea whats wrong and the debug message of my billing result is empty. As MeisterTea wrote, what are we supposed to do with the v3 behind forced to us from December 1? 

Thank you for your help.
