### ISSUE TITLE
IabHelper needs unit tests

### ISSUE THREAD

**Issue by tbook** [googlesamples/android-play-billing#24]
IabHelper is complicated enough (and frequently enough borrowed) that it needs unit tests to verify that things work correctly and prevent regressions.

**Comment by dkhmelenko** [comment]
is there any plan to take an action on this issue?

**Comment by netomarin** [comment]
Hi @tbook 
This app is a sample implementation for In-App Billing API, and should not be used on production apps as is. We have no plans to add unit tests.

Best regards.
