### ISSUE TITLE
flagStartAsync / flagEndAsync - why not just AsyncTask & SERIAL_EXECUTOR ?

### ISSUE THREAD

**Issue by pnico** [googlesamples/android-play-billing#39]
I'm seeing this a lot
`Can't start async operation (refresh inventory) because another async operation (refresh inventory) is in progress`

flagStartAsync and flagEndAsync are called from different threads, but `synchronized` does not guarantee order of execution, and they will definitely break if they get called out of order. If you used AsyncTask instead, you wouldn't have to worry about this, everything would just be queued and execute in the proper order.

Please correct me if I am missing something..

**Comment by netomarin** [comment]
Can not reproduce.
Not sure if this issue is about this sample.

Best regards.
