### ISSUE TITLE
Why this code is different of the one in the sdk ?

### ISSUE THREAD

**Issue by benju69** [googlesamples/android-play-billing#41]
Why this github is project is not exactly the same as the sample in the sdk ?(.../Android/sdk/extras/google/play_billing/ ... TrivialDrive ...)
Should I use this one instead the old code ?

**Comment by netomarin** [comment]
Hi @benju69 

The code from SDK was moved to here, and never more got updated.
Soon we will remove it from the SDK.

Hope I answered your question.
Thanks.
