### ISSUE TITLE
IabHelper.dispose() can cause crashes in pending async operations

### ISSUE THREAD

**Issue by kplatfoot** [googlesamples/android-play-billing#5]
The IabHelper class has a dispose() method that does various cleanup tasks (unbinds the ServiceConnection, nulls out instance fields, etc). This method is intended to be called from the host activity's onDestroy method. IabHelper also includes *Async methods that can perform billing operations on a background thread. However, this combination produces a race condition that can cause runtime crashes. If dispose() is called while an async operation is in progress, the async operation may crash, e.g. because mDisposed is false (IllegalStateException) or mContext is null (NullPointerException).

I've seen crash reports like from my Android app running in production. I fixed the problem in my app by having dispose() check whether an async operation is in progress, and if so, defer the dispose until after it finishes. I've created a similar patch for the android-play-billing sample project.

**Comment by PaulRashidi** [comment]
Thanks for flagging this. Please send over the pull request and sign the CLA after the CLA bot adds it to your pull request.

**Comment by jkane001** [comment]
@PaulRashidi I believe this one is resolved with this PR: https://github.com/googlesamples/android-play-billing/pull/6

**Comment by PaulRashidi** [comment]
Yep, thanks!
