### ISSUE TITLE
In-app Billing

### ISSUE THREAD

**Issue by Me-109** [googlesamples/android-play-billing#52]
I would like to ask Kazakhstan Zhuo mobile phone users to the root of the phone or can be purchased inside the google play it, googel paly will not limit the purchase of the root phone it Thank you

**Comment by netomarin** [comment]
This issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.
