### ISSUE TITLE
Memory Leak IabHelper.startSetup()

### ISSUE THREAD

**Issue by alistairsykes** [googlesamples/android-play-billing#54]
While using this set of util classes we think we found a memory leak for our use case.

---

**In our use case:**
We call `mHelper.startSetup(this);` from within the `onCreate()` of our activity. However also within the `onCreate()` we call `setRequestedOrientation();` which may well cause our activity to be quickly destroyed, before the `IabHelper.OnIabSetupFinishedListener.onIabSetupFinished(IabResult result)` has been called. This means that the `IabHelper` is holding a reference to our activity in the form of a `OnIabSetupFinishedListener` past the life time of our activity.

**The solution for us was:**

- Add a local field to the `IabHelper` as follows: `OnIabSetupFinishedListener mSetupListener;`.

- Then in the `startSetup(OnIabSetupFinishedListener listener)` set the reference for this field as follows:  `mSetupListener = listener;`

- Then still within `startSetup(OnIabSetupFinishedListener listener)` update the `mServiceConn` to reference the new field instead of `listener` directly (there are three places this happens).

- Then in the `dispose()` method we did `mSetupListener = null;`.

---

I am aware this may not suffice as a broader solution because if `startSetup()` is called more than once then there could still be a memory leak however in our use case we are confident we dont do that.

Hope this helps someone else.

**Comment by netomarin** [comment]
Hi @alistairsykes 

Thanks for sharing your experience.
Just to mention, in our sample we avoid the leak with some lines in onDestroy method:

// very important:
Log.d(TAG, "Destroying helper.");
if (mHelper != null) {
    mHelper.disposeWhenFinished();
    mHelper = null;
}

And because this issue is not exactly related to this sample, I'm closing the issue.
Again, thanks for your contribution.
Thanks.

**Comment by alistairsykes** [comment]
FYI: I was also using those lines in on destroy but they did not fix the problem. Is there a more appropriate repository I can raise this on, this was the only one I found.

**Comment by netomarin** [comment]
Hi @alistairsykes 

If it's something in your code and you want help to fix it, I suggest to use online communities like Stackoverflow and use the tags google-play and in-app-purchase. We are trying to answer the questions there, and also you have all community support.

If it's something you think is wrong in our side, you always can use the live chat or e-mail contact from Google Play Console, clicking on the "?" at the top right corner.

Thanks
Neto
