### ISSUE TITLE
How can i get purchase history ? (TrivialDrive_v2)

### ISSUE THREAD

**Issue by ibrahim132** [googlesamples/android-play-billing#56]
We need to get user purchase history (Subscriptions history). Can we do this using (TrivialDrive_v2) ?

**Comment by gorgon** [comment]
TrivialDrive v2 is just a demo app of basic functionality for the new Play Billing Library.
You can read more about it [here](https://developer.android.com/google/play/billing/billing_library.html).
This library also allows to get purchase history even though it's not demonstrated inside this sample. Please use [this method](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.html#queryPurchaseHistoryAsync(java.lang.String, com.android.billingclient.api.PurchaseHistoryResponseListener)) to get all purchases history (1 per SKU).
