### ISSUE TITLE
Getting "IAB helper is not set up" even after the setup returns a success

### ISSUE THREAD

**Issue by swapnilgt** [googlesamples/android-play-billing#58]
I recently integrated the in-app-billing code into my app and I have some crashes reported in my Crashalytics system saying `Fatal Exception: java.lang.IllegalStateException: IAB helper is not set up. Can't perform operation: queryInventory` even after the callback for setting it up returns success. Here is my code for setting the `IabHelper`:

```
public void setupPayments() {
        mHelper = new IabHelper(MyApplication.applicationInstance,
                Utils.getAppBilllingLicenseKey());
        mHelper.startSetup(new IabHelper.OnIabSetupFinishedListener() {
            @Override
            public void onIabSetupFinished(IabResult result) {
                // Setting is the payment is setup or not ..
                isPaymentsSetup = result.isSuccess();
                if(mSetupListener != null) {
                    mSetupListener.onSetupFinished(result.isSuccess(), result);
                }
            }
        });
    }
```
On receiving the callback, I perform the following action:

```
@Override
    public void onSetupFinished(boolean success, IabResult result) {
        if(success) {
            MyApplication.applicationInstance.getmInAppPurchaseUtils()
                    .triggerCheckAdsFreePurchase();
        } else {
            MyApplication.applicationInstance.setmShowAds(true);
            Timber.d("Setting up of the payments was failed. Directly taking to the app");
            checkInternetAndTakeAction();
        }
    }
```

The code for `triggerCheckAdsFreePurchase` is:
```
public void triggerCheckAdsFreePurchase() {
        try {
            mHelper.queryInventoryAsync(mAdsFreeSubscriptionListener);
        } catch (IabHelper.IabAsyncInProgressException e) {
            if(mInventoryAdsFreeSubscriber != null) {
                mInventoryAdsFreeSubscriber.onQueryInventoryException(e);
            }
        }
    }
```

So, with this code I am getting the Exception: `Fatal Exception: java.lang.IllegalStateException: IAB helper is not set up. Can't perform operation: queryInventory`.  Do I have any errors in my code? If not, I have come across some posts to handle this. [This](https://stackoverflow.com/a/15311214/2606411) one gives a solution. Is this the only workaround for now?

**Comment by axper** [comment]
I have exact same problem, any updates?

**Comment by sonngaytho** [comment]
I'm getting same error even if I have checked set-up-Done and Async-Not-In-Progress.
Any idea?

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

[Stackoverflow](https://stackoverflow.com/questions/tagged/in-app-billing) might be a better forum.

Please reopen if you still think this is an issue with the sample.
