### ISSUE TITLE
IabHelper.java does not call getPurchaseHistory()

### ISSUE THREAD

**Issue by tucson-tom** [googlesamples/android-play-billing#60]
Trivial Drive is the defacto standard implementation of IAB referenced by the documentation.  However it is incomplete since it does not support detecting previously consumed SKUs.  Let's suppose you have a group of related items any of which can be purchased multiple times in the same app on the same device but only one of the SKUs in the group have to be purchased to access a specific feature.  To allow the user to purchase multiple times, the app has to consume the purchases as they happen.  However, once the app has consumed the purchase, `IabHelper.queryInventory()` no longer returns the SKU in its list.

To solve this, `Purchase` should be extended to have a `mIsConsumed` variable and an 'isConsumed()' method to allow the application to determine if the most recent purchase of an item has already been consumed and `IabHelper.queryInventory()` extended to support the updated Purchase class (e.g. adding a `boolean consumed` to the method so the caller can decide whether or not they want already consumed items in the results).

**Comment by pfmaggi** [comment]
Please refer to ClassyTaxy And Trivial Drive 2.

Closing as obsolete.
