### ISSUE TITLE
Trivial Drive in Google Play

### ISSUE THREAD

**Issue by tucson-tom** [googlesamples/android-play-billing#61]
Searching for "Trivial Drive" in Google Play turns up some really shady results.  Since this application is tied to in-app purchasing and is intended only as an example not for publishing as-is, those apps should not be allowed to persist in Google Play.

This might be a violation of Section 5.5 of the developer agreement which says, "You agree that you will not submit material to Google Play that is copyrighted ... or have permission from their rightful owner to submit the material."  Google should not grant permission to publish its own sample IAB Trivial Drive example as-is within the Google Play ecosystem.

**Comment by pfmaggi** [comment]
Please refer to ClassyTaxy And Trivial Drive 2.

Closing as obsolete.
