### ISSUE TITLE
Service Intent must be explicit

### ISSUE THREAD

**Issue by fillobotto** [googlesamples/android-play-billing#62]
I'm getting this exception:
`java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.android.vending.billing.InAppBillingService.LOCK (has extras) } at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1711) at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1810) at android.app.ContextImpl.bindService(ContextImpl.java:1788) at android.content.ContextWrapper.bindService(ContextWrapper.java:539) at com.android.billingclient.api.BillingClientImpl.startConnection(SourceFile:153)`

It happens when a user tries to crack the billing system using tools like Freedom and similar. It can be fixed by simply explicitly declaring the package name when sending the intent.

**Comment by fillobotto** [comment]
Anyone?

**Comment by gorgon** [comment]
Are you using [new Play Billing library](https://developer.android.com/google/play/billing/billing_library.html) or modified TrivialDrive sample?
From what I see, they both explicitly define the package inside serviceIntent:
`serviceIntent.setPackage("com.android.vending");`

**Comment by fillobotto** [comment]
I am using the new library. Well, the number of crashes is low but it also happens on startup when checking purchases and it's not good that the app crashes even though the user has installed illegal software on his device. You should look into this

**Comment by gorgon** [comment]
My guess is that hack tools sometimes are removing explicit package name from the intent on the fly and trying to represent themselves as a Play Store.
So there is not much we can do except including other explicit variables inside the intent in next library release, but they can also be removed.
I think the best solution for developers would be catch IllegalArgumentException from `BillingClient.startConnection` method.
And for security we strongly recommend using [our backend API](https://developers.google.com/android-publisher/api-ref/purchases/products/get) for all purchases verification.

**Comment by ashughes** [comment]
FYI, while I understand why it's recommended to use the backend API for purchase verification, this only really works if the app has user sign-in and a backend.

**Comment by fillobotto** [comment]
@gorgon of course I am using backend verification with PHP code. I just wanted to know if there was a gentle way to solve the crash without having to catch the Exception explicitly on my side.

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

[Stackoverflow](https://stackoverflow.com/questions/tagged/in-app-billing) might be a better forum.

Please reopen if you still think this is an issue with the sample.
