### ISSUE TITLE
Non-renewable subscription and tracking

### ISSUE THREAD

**Issue by Hiteshsaini1993** [googlesamples/android-play-billing#65]
I want to implement a non-renewable subscription in the app. I have two types of subscriptions in my app and when the other will be selected then the previous one must be cancelled but I am not able to find a solution for this.

**Comment by gorgon** [comment]
Renewable subscription does exist and it's called [managed in-app product](https://developer.android.com/google/play/billing/billing_overview.html#products).
You can't cancel the subscription by yourself, but there is a subscription replace mechanism, that should fulfill your use case. For this you just need to specify old subscription SKU (via [this API](https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder.html#setOldSkus(java.util.ArrayList<java.lang.String>))) when the user is starting a new subscription.

**Comment by Hiteshsaini1993** [comment]
Thank you for the suggestion. I will try this.

**Comment by Hiteshsaini1993** [comment]
I tried the same thing you suggested with the same code given in this repository but now the problem is coming "Error while retrieving information from the server [DF-DIC-02]". Please help me solve this issue.

**Comment by gorgon** [comment]
Sounds like there are some problems with your SKUs/product IDs or signing of your app. I recommend:
1. Try to allocate your account as a license tester first: read "Setting up test purchases" chapter from here: https://developer.android.com/google/play/billing/billing_testing.html
2. Make sure you setup all of your SKUs/product IDs correctly on Google Play Console: https://developer.android.com/google/play/billing/billing_admin.html
3. Consider integration with IAB using new Play Billing library that makes this process easier and more reliable: https://developer.android.com/google/play/billing/billing_library.html

**Comment by pfmaggi** [comment]
Please refer to ClassyTaxy And Trivial Drive 2.

Closing as obsolete.
