### ISSUE TITLE
Simplify removal of IAB test purchases

### ISSUE THREAD

**Issue by tucson-tom** [googlesamples/android-play-billing#68]
I realize this probably isn't the right place to make this request but I don't know where this request should be directed to.

Android Developer mode should allow removal/consumption of IAB test purchases from within `Settings -> Manage Apps`.

The current requirement to modify the app to add a button to consume test purchases and remembering to remove the button prior to publishing is tedious (at best).  Being able to select individual test items from the global Settings app to consume them would make this process much more manageable.

**Comment by djreep81** [comment]
I second this.

The work around I came up with is the same.  I deploy my application out to Alpha that consumes test purchases.  I have to remove that consume code when pushing out to other environments.  This solution is a recipe for disaster.  I would also like a cleaner solution to this as well.

**Comment by afehners** [comment]
For testing I have code guarded with
`if( BuildConfig.BUILD_TYPE.equalsIgnoreCase("debug")) { ...}`

which will make a button .VISIBLE, which I can tap to consume the InApp purchases

**Comment by tucson-tom** [comment]
@afehners That doesn't work.  It's not possible to test real in-app products without a signed binary in Google Play.  This issue is requesting Google to address the problem at the system level.  There shouldn't be any special coding required to consume test purchases, period.

**Comment by gorgon** [comment]
I think solution from @afehners makes a lot of sense.
It's hard for Google to implement this, taking into account various security issues related to consuming items from 3rd party apps.

**Comment by tucson-tom** [comment]
@gorgon Test items don't have an orderId.  They are easy enough to identify and there are zero security issues with consuming them.  It isn't possible to create a test order in the first place without that user being specifically defined in Google Play as a test IAB user.  The solution provided simply does not work because only signed release mode binaries can be used to test IAB with real products.  The test codes are nearly useless for legitimate testing.

**Comment by gorgon** [comment]
First, you can upload a signed release binary, but still test with signed debug binary if it has the same app signature and version code.
Second, you can set your account [as a license tester](https://developer.android.com/google/play/billing/billing_admin.html#billing-testing-setup) and then there is no need to signing your application at all as far as a valid signed application is uploaded into Play Console with the same app version.

**Comment by pfmaggi** [comment]
Please refer to ClassyTaxy And Trivial Drive 2.

Closing as obsolete.
