### ISSUE TITLE
Fix IAB getPurchases() API

### ISSUE THREAD

**Issue by tucson-tom** [googlesamples/android-play-billing#70]
I realize this probably isn't the right place to make this request but I don't know where this request should be directed to.

The IAB getPurchases() API does not include the total amount and currency used to purchase an item as well as separation of fees (including Google's take).  This is necessary information for a variety of accounting and validation purposes.  Relying on the SKU details is insufficient since the user might not have paid the amount currently stored in the SKU (promo codes, price changes, market conditions, etc).

This should be flagged as critical priority as it affects certain financial reconciliation processes.

**Comment by pfmaggi** [comment]
Please refer to ClassyTaxy And Trivial Drive 2.

Closing as obsolete.

Please reopen if you think this issue is still relevant.
