### ISSUE TITLE
Error retrieving data from server

### ISSUE THREAD

**Issue by Hiteshsaini1993** [googlesamples/android-play-billing#73]
I have implemented two different subscriptions in my app with the same code you have provided. I have generated the release apk and added to the alpha testing. Now when I am trying to test that on emulator then the app is crashing and "In-app Billing setup failed: IabResult: Billing service unavailable on device. (response: 3:Billing Unavailable)" this error is coming and when I am trying to test that on my device then "Error while retrieving information from server [DF-DIC-02] error is coming".

**Comment by gorgon** [comment]
Sounds like there are some problems with your SKUs/product IDs of signing of your app. I recommend:
1. Try to allocate your account as a license tester first: read "Setting up test purchases" chapter from here: https://developer.android.com/google/play/billing/billing_testing.html
2. Make sure you setup all of your SKUs/product IDs correctly on Google Play Console: https://developer.android.com/google/play/billing/billing_admin.html
3. Consider integration with IAB using new Play Billing library that makes this process easier and more reliable: https://developer.android.com/google/play/billing/billing_library.html

**Comment by Hiteshsaini1993** [comment]
I have my app in alpha testing and there is an option to manage testers I have added my mail account in that and also in the license tester but still the same error is coming. The SKUs/product IDs are correctly setup on google play but I still don't know why this error is coming.

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

[Stackoverflow](https://stackoverflow.com/questions/tagged/in-app-billing) might be a better forum.

Please reopen if you still think this is an issue with the sample.
