### ISSUE TITLE
Please check the result of the bindService()

### ISSUE THREAD

**Issue by serhii-k** [googlesamples/android-play-billing#75]
https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive/app/src/main/java/com/example/android/trivialdrivesample/util/IabHelper.java#L301

bindService() can return **false**

For example, on some Chinese phones their native "security" apps block Play Store. So, even though it's installed on a device, it's not guaranteed you can bind to the Play Store service.

So, should be something like:
            boolean result = mContext.bindService(serviceIntent, mServiceConn, Context.BIND_AUTO_CREATE);
            if (!result) {
                mContext.unbindService(mServiceConn);
                mServiceConn = null;
                if (listener != null) {
                    listener.onIabSetupFinished(
                            new IabResult(BILLING_RESPONSE_RESULT_BILLING_UNAVAILABLE,
                                    "Could not bind to the the billing service."));
                }
            }

**Comment by gorgon** [comment]
Thank you for your feedback.
We implemnted your suggestion inside [Play Billing library 1.0 release](https://android-developers.googleblog.com/2017/09/google-play-billing-library-10-released.html).

**Comment by serhii-k** [comment]
Thank you very much!
