### ISSUE TITLE
sdk callback  message is  “User Canceled”， but the order pay succeed in the Google play Console

### ISSUE THREAD

**Issue by keenlee123** [googlesamples/android-play-billing#76]
sdk callback  message is  “User Canceled(response :-1005:User Canceled )”， but the order pay succeed in the Google play Console;

**Comment by DusanSp** [comment]
Same issue here. I start purchase flow click buy and then turn off wireless. I receive pay succeed and in google play console purchase is stored, but when I call getAllPurchasess response is null.

**Comment by keenlee123** [comment]
Reboot  your phone ,then you may get the response.

**Comment by DusanSp** [comment]
Thank you, that helped.

**Comment by gorgon** [comment]
@keenlee123, are you still having the same problem? Is it constantly reproducible? Could you please give us the detailed steps?

**Comment by mciarcia-nav** [comment]
@gorgon I had the same issue, the user provided us with valid payment but the application received User Canceled(response :-1005:User Canceled ). 
I don't have any detailed steps but different customer complaints.
Is there any way to retrieve the consumable purchase in this condition?

**Comment by gorgon** [comment]
Is your app always queries for purchases on start up? This will be the first solution.
And if the purchase was somehow consumed but after this your app crashed or something enormous happened, then such problems could be solved by [querying purchase history](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.html#queryPurchaseHistoryAsync(java.lang.String, com.android.billingclient.api.PurchaseHistoryResponseListener)). And if your app ever found a purchase that was not taken into account, then handle it. Plus we have [corresponding backend API](https://developers.google.com/android-publisher/api-ref/purchases/voidedpurchases/list) to verify it.

**Comment by keenlee123** [comment]
@gorgon  For one online user complaints us, we found this problem. We currently only  found this user.  When pay and then turn off wireless.This Step can  reproduce. I cannot confirm the online user's condition. Is there any way to Avoid this problem?

**Comment by pfmaggi** [comment]
Please refer to ClassyTaxy And Trivial Drive 2.

Closing as obsolete.

Please reopen if you think this issue is still relevant.
