### ISSUE TITLE
Play Billing Library - developerPayload support.

### ISSUE THREAD

**Issue by gswierczynski** [googlesamples/android-play-billing#78]
Hi,

It's probably not the best place to ask this, but I am not sure where else I can put it.

Can we expect support of developerPayload in the Android Billing Library?
Currently BillingClient class passes null as developerPayload.

I realise that it's dp-1.
Just wondering if I should wait for another release or drop using library for now.

Thanks,
Greg.

**Comment by gang018** [comment]
Hi @gswierczynski 
Look at method **setAccountId()** of class **BillingFlowParams**. May bee it can be used as **developerPayload**.
The docs says: 

> Specify an optional obfuscated string that is uniquely associated with the user's account in
> your app.
> 
> If you pass this value, Google Play can use it to detect irregular activity, such as many
> devices making purchases on the same account in a short period of time. Do not use the
> developer ID or the user's Google ID for this field. In addition, this field should not
> contain the user's ID in cleartext. We recommend that you use a one-way hash to generate a
> string from the user's ID and store the hashed string in this field.

**Comment by gswierczynski** [comment]
Hi @gang018,

Thanks, I have noticed this method, but verified that value passed as parameter it is not passed as a developer payload and later cannot be retrieved from API response on the server side.

**Comment by gswierczynski** [comment]
Hi,

I would love to know your take on this. Is this something that will be done.

The way I see it, it is fairly simple to add another method BillingFlowParams.Builder that would allow passing developer payload to the API.

Or you do not plan to support developer payload. Is it not going to be available in the future and we just do not know about it?

Cheers,
Greg.

**Comment by crossle** [comment]
Same problem no developer payload, not passed by server verify, plz add back developer payload

**Comment by gswierczynski** [comment]
@crossle - just to clarify - the developerPayload is still supported. If you would use the API directly everything is OK. It is just that the Play Billing Library does not expose it (there is no way to set it during purchase request).

**Comment by crossle** [comment]
@gswierczynski, thanks, i migrate to Play Billing library, found no method set developer payload

**Comment by gswierczynski** [comment]
@gorgon Any chance you could let us know, if developerPayload will be supported by the library?

**Comment by gswierczynski** [comment]
I received anwser on the bugtracker pointing me to another issue:
https://issuetracker.google.com/issues/63381481

Gist is:
Developer Payload is a legacy field, might become deprecated and removed at some point.
Will not be supported by the Play Billing library.

I always considered it something additional that was checked on the server side (verification that user processing purchase on server was the same as the one initiating it).

**Comment by tianxiatianshan** [comment]
May i kown when the DeveloperPayload might be deprecated?

**Comment by Mahmoood** [comment]
Finally the v2 of the billing library supports developer payload.

**Comment by candyluo** [comment]
> 最后，计费库的v2支持开发人员有效负载。

v2是什么版本？

**Comment by linsea** [comment]
> Finally, the v2 of the billing library supports developer payload.

Do you mean the `BillingFlowParams.Builder.html#setDeveloperId(java.lang.String)`  method ?
https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder.html#setDeveloperId(java.lang.String)

**Comment by gswierczynski** [comment]
> Note, however, that you can attach a developer payload only when the purchase is acknowledged or consumed.

So it is not something you specify when you build BillingFlowParams.

Documentation:
https://developer.android.com/google/play/billing/billing_library_overview#attach_a_developer_payload
