### ISSUE TITLE
Gradle sync failed: Application and test application id cannot be the same: both are 'com.example.billingsample' for debugAndroidTest

### ISSUE THREAD

**Issue by DimaKoz** [googlesamples/android-play-billing#80]
I've got `Gradle sync failed: Application and test application id cannot be the same: both are 'com.example.billingsample' for debugAndroidTest` when I cloned this repo and tried to open [TrivialDrive_v2].
My Android Studio is:
<img width="285" alt="this Android Studio" src="https://user-images.githubusercontent.com/3092276/30632699-b947653a-9df1-11e7-82b2-31455889aa71.png">

**Comment by obigu** [comment]
Happens also importing project following official documentation from https://developer.android.com/training/play-billing-library/preparing-iab-app.html

> 1. In Android Studio, select File > New > Import Sample.
> 2. Type Trivial Drive into the search bar and select the TrivialDrive_v2 sample. Follow the rest of the wizard to import the sample to a directory of your choosing.

**Comment by volt255** [comment]
change the testApplicationId in the build.gradle located in base-feature to : 

testApplicationId "test" //project.APP_ID
