### ISSUE TITLE
Retrieve SKUs Introductory prices?

### ISSUE THREAD

**Issue by MinaSamy** [googlesamples/android-play-billing#81]
Hello,

The In-App billing service provides a method to retrieve the products introductory prices via the [getSkuDetails()](https://developer.android.com/google/play/billing/billing_reference.html#getSkuDetails) method.

Is there a similar way in the new [Play Billing Library](https://developer.android.com/google/play/billing/billing_library.html) to retrieve those introductory prices?

**Comment by gorgon** [comment]
Yes, it's called querySkuDetailsAsync.
Please see full Javadoc here: https://developer.android.com/reference/com/android/billingclient/api/BillingClient.html

**Comment by ashughes** [comment]
@gorgon Except [SkuDetails](https://developer.android.com/reference/com/android/billingclient/api/SkuDetails.html) in the Play Billing Library does not contain trial information. I filed a bug on this yesterday: https://issuetracker.google.com/issues/65966431

**Comment by gorgon** [comment]
Yes, it was a bug and it's fixed now. So please [clear your gradle cache](https://stackoverflow.com/a/30450020/1390874) and rebuild the app.
Then you should be able to get all of the SKU details.

We'll update our [reference page](https://developer.android.com/reference/com/android/billingclient/api/SkuDetails.html) in a couple of days.

**Comment by MinaSamy** [comment]
Hi,
I'm just wondering if the introductory prices fix has been rolled yet. I checked as mentioned in the last comment but still can't access the introductory prices

**Comment by gorgon** [comment]
Yes, 1.0 release was updated 1 week ago.
Make sure that you cleared your gradle cache and all of build files prior to rebuilding your app.

**Comment by MinaSamy** [comment]
Thanks a lot, it's resolved now
