### ISSUE TITLE
error: SkuDetailsResult is not public in SkuDetails; cannot be accessed from outside package

### ISSUE THREAD

**Issue by volt255** [googlesamples/android-play-billing#82]
I downloaded the sample, 

changed the  testApplicationId in the build.gradle located in base-feature to : testApplicationId "test" //project.APP_ID
to remove the "Gradle sync failed: Application and test application id cannot be the same: both are 'com.example.billingsample' for debugAndroidTest"

I closed android studio and reopen, now the Android gradle plugin wants to update to version 3.0.0-beta6 and Gradle to version 4.1, which i did

now i get this error:

Error:(146, 57) error: SkuDetailsResult is not public in SkuDetails; cannot be accessed from outside package

**Comment by gorgon** [comment]
Just remove SkuDetailsResult. It is not exposed in Billing Library 1.0 release and shouldn't be used. The result is delivered by the list of [SkuDetails](https://developer.android.com/reference/com/android/billingclient/api/SkuDetails.html) objects without any wrappers.
Please see all the changes at [1.0 release notes](https://developer.android.com/google/play/billing/billing_library_releases_notes.html).
