### ISSUE TITLE
isAutoRenewing() always returns false

### ISSUE THREAD

**Issue by gang018** [googlesamples/android-play-billing#84]
Hello!

I'm using method **queryPurchaseHistoryAsync()** to query user's purchases history which includes subscription. The results of the method does not contain **autoRenewing** key in JSON, so **isAutoRenewing()** always returns false. It's very unuseful, because I want to know user cancelled his subscription or did not.

**UPD:**
I'm using     compile 'com.android.billingclient:billing:1.0'

**Comment by gang018** [comment]
Interesting fact: I have **autoRenewing** flag if I use **queryPurchases()**.

**Comment by gorgon** [comment]
autoRenewing is [not a part of purchase history API](https://developer.android.com/google/play/billing/billing_reference.html#getPurchaseHistory). It's just a historical status.
If you want to know whether the user canceled or not, you should [query purchases](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.html#queryPurchases(java.lang.String)).

**Comment by gang018** [comment]
Ok, solved my problem using **queryPurchases()** instead of **queryPurchaseHistoryAsync()**

**Comment by AdityaAnand1** [comment]
Oh my god! Wow! What an astounding mess! I Just spent ~5 hours debugging this!

Literally no mention of this anywhere in the docs! 

I'm a patient guy, but really, the billing API is right up there with Fragments and MediaPlayer and ContentResolver.

Wow!

Fwiw, the documentation needs to mention this in BIG BLACK screaming bold letters. And why was this issue closed? Turning a method from Async to sync should not change the result!

Wow!

**Comment by PaoloGi** [comment]
this issue is still present in 1.2.
isAutoRenewing is an important field and it would be useful to check from queryPurchaseHistoryAsync since this is a direct query to google and not from the cache of the play store like queryPurchases

**Comment by ashishb** [comment]
FWIW, it is Aug 2023 and this is still broken.
