### ISSUE TITLE
Items consuming process

### ISSUE THREAD

**Issue by F0RIS** [googlesamples/android-play-billing#85]
I'm making consumable items in my game (buying coins). Coins stored in database which under managment of my API. The question is: at what phase of purchasing and consuming I must send request to my API? I wanna make fail safe system. How to manage if google play returned fail during consuming (connection problems for example) or my api for some reason fails too (was restarting for example).

Or what is the right way to tackle this? May be using history method or something like that?

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

[Stackoverflow](https://stackoverflow.com/questions/tagged/in-app-billing) might be a better forum.

Please reopen if you still think this is an issue with the sample.
