### ISSUE TITLE
No interface method getBuyIntentExtraParams - billing v1.0

### ISSUE THREAD

**Issue by NodensN** [googlesamples/android-play-billing#86]
I would like to use the new Google play billing library `com.android.billingclient:billing:1.0`

But when I run:
```java
final BillingFlowParams.Builder builder = BillingFlowParams.newBuilder()
        .setSku(sku)             
        .setType(BillingClient.SkuType.SUBS); 
int resultCode = mBillingClient.launchBillingFlow(activity, builder.build());
```
I've this issue :
```java
Caused by: java.lang.NoSuchMethodError: No interface method getBuyIntentExtraParams(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Landroid/os/Bundle;)Landroid/os/Bundle; in class Lcom/android/vending/billing/IInAppBillingService; or its super classes (declaration of 'com.android.vending.billing.IInAppBillingService' appears in /data/app/{MY_PAKAGE_NAME}-eHTcC-Sp4zY08KZcxkl7fQ==/base.apk:classes97.dex)
```

`BillingClientImpl.java:332`

Any ideas?

**Comment by gorgon** [comment]
Which device are you using?

**Comment by NodensN** [comment]
@gorgon Nexus 5x on Android 8.0.0

**Comment by gorgon** [comment]
Seems, like it's something wrong with that build. Could you please try a phone with an official OTA Android release?

**Comment by NodensN** [comment]
Nexus 5x Build number OPR4.170623.006 is not an official OTA release? 
I'm in the Android Bêta program you think it would be the reason?

**Comment by NodensN** [comment]
Missclick... -_-'

**Comment by gorgon** [comment]
Yes, "Beta" doesn't sound very official =)

**Comment by NodensN** [comment]
Ok I found why. It's not a problem with the Android build of the device. 
It's because there already was an `IInAppBillingService.aidl` in our project. Once I removed it and clean the project everything is working properly.
