### ISSUE TITLE
Infinite loop observed after interrupting the IAP purchase dialog with Multitask button.

### ISSUE THREAD

**Issue by Kurnosov** [googlesamples/android-play-billing#87]
1) Run purchase dialog by tapping  Buy Gas button;
2) On purchase dialog loading perform multitask interrupt (when loading circle observed on purchase dialog);
3) Wait up to 5 sec and return to Trivial drive;
4) Observe infinite loading of purchase dialog.
![1](https://user-images.githubusercontent.com/1555625/30899207-98d318d2-a367-11e7-85e2-082dbccda7f7.gif)

**Comment by pfmaggi** [comment]
Obsolete
