### ISSUE TITLE
Account authentication errorr

### ISSUE THREAD

**Issue by quantumalh** [googlesamples/android-play-billing#9]
when doing inapp purchases in sample , error dialog appear , you need to sign in to your google account.

**Comment by PaulRashidi** [comment]
Hi, could you be a little more specific? Are you saying an error dialog is preventing the Google Account  Login from appearing? If so, the most common issue there is resolved by following the steps in the README to register your application's package, sha1, and contact information (even for just deploying a debug/sample app). Seems odd for a sample, but Google Play can't display a consent screen if it doesn't know anything about the app and that registration is how it knows who owns the app.

**Comment by PaulRashidi** [comment]
I'm going to close this for now, but open it back up with more information if you continue to have an issue.

**Comment by quantumalh** [comment]
it is fixed thank you!
