### ISSUE TITLE
Where's the updated code to use the new Google Play Billing Library?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-play-billing#91]
It's written [here ](https://android-developers.googleblog.com/2017/09/google-play-billing-library-10-released.html)that it got updated, but all I see here is old code...

What's going on?

**Comment by AndroidDeveloperLB** [comment]
If it's the "TrivialDrive_v2" , that's very different from what we had before, and doesn't seem trivial at all.
What's the easiest way to switch from the previous one to the new one?
Do they even match in some way?
I used to do all with IabHelper , but now it's gone here...
There's no onQueryInventoryFinished, there's no OnIabPurchaseFinishedListener ...
And still, I don't see a way to test this library on a real device, without a real credit card that does real purchasing, on an account that's not of the developer...

**Comment by gorgon** [comment]
Unfortunately, old TrivialDrive had many problems and we wanted to encourage developers to use best practices in Android development in new sample app.
But if its code is too complicated for you, you don't need to study it completely.
Just see, how we did an integration with Play Billing library inside [BillingManager.java](https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive_v2/shared-module/src/main/java/com/example/billingmodule/billing/BillingManager.java).

**Comment by AndroidDeveloperLB** [comment]
Well I was excited to try the new version because the previous one seem to have some issues (thought it has bugs fixes along with a nice wrapping into Gradle repo).
But now it's very different.
Is there any way to try the sample app (and also my app) on a real device, using my own account, as if it really does the purchases, yet on a debug version of the app ?
On the previous API, I remember I tried this and failed. The only way to really see it in action, was to use a different account, with a signed APK, with a real credit card being used. 
This was terrible in terms of testing it out. 
There was a small alternative. Don't remember its name, but it was very different than how IAP works.

Is there perhaps a minimialized version of the sample?

**Comment by AndroidDeveloperLB** [comment]
Suppose I have the SKUs, and the IAP key.
How do I do the basic things (purchase, get purchases, consume purchase)?
What's the easiest way to migrate from the previous API ?

**Comment by gorgon** [comment]
Please see [corresponding documentation page](https://developer.android.com/google/play/billing/billing_library.html) with examples, training and references.

**Comment by AndroidDeveloperLB** [comment]
I don't see the part of the IAP key we had on previous API. Was it removed? Is it no longer needed or recommended?

**Comment by oRRs** [comment]
gorgon already pointed you to the implementation that is somewhat comparable to the old IabHelper ([BillingManager.java](https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive_v2/shared-module/src/main/java/com/example/billingmodule/billing/BillingManager.java)). That also includes the `BASE_64_ENCODED_PUBLIC_KEY` which is probably what you mean with the "IAP key".

**Comment by AndroidDeveloperLB** [comment]
Why is my comment downvoted?
I was given a link to the documentation, but there is no IAP key being mentioned there (or any key whatsoever).
