### ISSUE TITLE
Making Purchase with Particular Google Account

### ISSUE THREAD

**Issue by abumoallim** [googlesamples/android-play-billing#93]
I am having an application Name **X** with **Google Sign In**. Everything works on **user-selected google account** while logging.

Now if suppose user have 3 Google accounts on his/her phone say **A, B, C**. 
Now **account A** is connected to **google play store**. As a user, if I **logged** in with **Account B** in my **X App** and When I will make a **In-App purchase**, it will Make a purchase on **Account A** automatically as it is connected to **my Play Store** **(Downloaded App with Account A but Logged in with B in my X App).**  

Now I want some means to connect this purchase with Google **Account B** rather than any other i.e. with Account I am currently Logged in within **X App**. Please respond me as soon as possible. I have a pending app to release as early as possible. Thank you

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.
