### ISSUE TITLE
Request: avoid using Activity

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-play-billing#95]
This can lead to memory leaks in case we use it as a singleton.

Instead, use your own Activity that's created on top of the current ones, and do there what you need in order to perform the needed operations.
It's enough for each function will have a parameter of a Context instead.

**Comment by gorgon** [comment]
In order to start an activity, Android needs activity.
Please check [here](https://developer.android.com/reference/android/app/Activity.html#startActivity(android.content.Intent)).

However, we don't keep a reference to your activity inside the our code and the only place, where we require it (but not the context) is [launchBillingFlow method](https://goo.gl/Kb35pU).

**Comment by AndroidDeveloperLB** [comment]
You've missed a few things here:
1. It's incorrect that to start an Activity, you need an Activity. A Context is enough.
2. You could have provided a better API, that prepares an Intent using a builder. Or at least name the function something that really says it starts an Activity. 
3. The code does have a field that contains the Activity: 
https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive_v2/shared-module/src/main/java/com/example/billingmodule/billing/BillingManager.java
This class cannot be converted to a Singleton or be referenced to, via a Singleton. 
4. In the current form of the sample, the BillingManager is re-created upon Activity re-creation, which is a waste because it will need to re-query everything all over again, including checking its state with the Play-Services. This can also lead to bad, temporary state, when changing orientation, because for a fraction of a second, the UI won't be in sync with the real purchasing state.

I think that there should be a high-level Singleton manager, that contains all the purchases, contain the way to generate the BASE_64_ENCODED_PUBLIC_KEY, allows to register to its events, ...

I think the BillingManager should be this class, but abstract one.

**Comment by gorgon** [comment]
The only way to start the activity without the Activity instance is by setting 

> Intent.FLAG_ACTIVITY_NEW_TASK

 which will lead to a separate set of problems.
I feel that you don't like TrivialDrive_v2 implementation and it's fine. It is just a sample app. Feel free to implement the appropriate solution inside your own application and thank you for your feedback.
Also, if you feel strong that your ideas will benefit the community, then you can provide a pull request to the existing TrivialDrive_v2 sample and our team will review it.

**Comment by AndroidDeveloperLB** [comment]
If it's modular and remembers its state, there shouldn't be any problem using this flag.

The only reason to must have an Activity (or Fragment) to start a new one, is if you use startActivityForResult, because you expect a result on its callback.

TrivialDrive_v2 implementation doesn't even work, and it will never work, because :
1. SDK still doesn't support testing its purchases.
2. Sample doesn't have a key that it can work with. Not even one for debugging.
3. SDK requires the app to really have the purchases set on the website, so it must be registered, so only a single developer in entire world could use it, because after that, the package name will be taken. Not only that, but to add more to the difficulties of learning or testing this sample, a release version must be used, together with an account of a different user, with a credit card that's not of the developer.

As far as I see it, Trivial_v2 has the same issues as previous one, yet it got even harder to use, because it requires a lot of modifications to make it work.

**Comment by gorgon** [comment]
Ok, I will escalate your feedback to our team.
And please, don't use TrivialDrive_v2.

**Comment by AndroidDeveloperLB** [comment]
I was hoping to learn from the sample, and copy-paste the parts that will probably be the same accross all apps, like I did with the older sample.
Do you mean that none of the classes there would be useful?
If so, can you please create a sample that can be a skeleton/template for all apps?
Maybe one that the TrivialDrive_v2 uses by extending classes from it?

**Comment by andrewclam1991** [comment]
I second @AndroidDeveloperLB 's request to remove the dependency on an Activity class in the launchBillingFlow() method, if possible.
 
Architecturally and conceptually I think the in-app-billing should be as close to my own back-end as possible, which means it should act like a component in the Model layer (I could almost swear I saw in-app-billing as a Firebase feature, given it has so many, sadly it isn't). This Activity dependency would pretty much invert my architecture, and I'm struggling to make this work. 

From peeking at the BillingClientImpl#launchBillingFlow()
```
      // We need an activity reference here to avoid using FLAG_ACTIVITY_NEW_TASK.
      // But we don't want to keep a reference to it inside the field to avoid memory leaks.
      // Plus all the other methods need just a Context reference, so could be used from the
      // Service or Application.
      activity.startActivity(intent);
```
Am I correct to assume that I can use the method a Service of Application class? How would one get a reference to a live activity in those situations?

**Comment by Yazon2006** [comment]
Current implementation of launchBillingFlow is awfull because of link to the activity. Totally agree with comments above.

**Comment by pfmaggi** [comment]
Please refer to ClassyTaxy.

Closing as obsolete.

Please reopen if you think this issue is still relevant.

**Comment by AndroidDeveloperLB** [comment]
@pfmaggi Can't use the new ClassyTaxy sample. It's too complex, and as always doesn't allow to run it:
https://github.com/googlesamples/android-play-billing/issues/171

**Comment by AndroidDeveloperLB** [comment]
Why can't you make a sample that we can all try, without complications?
