### ISSUE TITLE
Having issues with purchasing flow

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-play-billing#97]
I have 2 SKUs defined fine on the console.
I can query them just fine using this code:

                        List<String> skuList = new ArrayList<>();
                        skuList.add(...);
                        skuList.add(...);
                        mBillingClient.querySkuDetailsAsync(SkuDetailsParams.newBuilder().setSkusList(skuList).setType(SkuType.INAPP).build(), new SkuDetailsResponseListener() {
                            @Override
                            public void onSkuDetailsResponse(final int responseCode, final List<SkuDetails> skuDetailsList) {
                                // I get here the 2 items in the list, with all their details
                            }
                        });

However, when I use this:

        BillingFlowParams flowParams = BillingFlowParams.newBuilder()
                .setSku(...)
                .setType(SkuType.INAPP)
                .build();
        int responseCode = mBillingClient.launchBillingFlow(activity, flowParams);

I get BillingResponse.OK as result, but then I get a dialog telling me "The item you requested is not available for purchase" :

![image](https://user-images.githubusercontent.com/5357526/31855535-ca9edec6-b6b5-11e7-8e4c-7ec37719db14.png)

I tried it on both SKUs, and both have the same result.

How could it be?

Do note that I used the old API before switching to the new one of using gradle ( with this one: compile 'com.android.billingclient:billing:1.0' ).

Looking at the logs, I can see these lines:

10-21 23:19:21.722 16201-16201/com.lb.app_manager W/ProxyBillingActivity: Got purchases updated result with resultCode 0 and billing's responseCode: 1
10-21 23:19:21.774 16201-16201/com.lb.app_manager W/BillingHelper: Couldn't find purchase lists, trying to find single data.
10-21 23:19:21.774 16201-16201/com.lb.app_manager W/BillingHelper: Received a bad purchase data.
10-21 23:19:21.774 16201-16201/com.lb.app_manager W/BillingHelper: Couldn't find single purchase data as well.
10-21 23:19:21.774 16201-16201/com.lb.app_manager W/BillingHelper: Couldn't find purchase lists, trying to find single data.
10-21 23:19:21.774 16201-16201/com.lb.app_manager W/BillingHelper: Received a bad purchase data.
10-21 23:19:21.774 16201-16201/com.lb.app_manager W/BillingHelper: Couldn't find single purchase data as well.

Is there a better way to ask Google for help about this issue, other than here?

**Comment by AndroidDeveloperLB** [comment]
Never mind. Forgot how limited and restricted Google is in IAP.

Issues that I had on previous API in terms of development stayed here too:
1. Can't try new version of app. 
2. Can't debug app.
3. Can't use non-signed app.

This, and the same other annoyances still exist:
1. Can't purchase on my own account, my own device and credit card.
2. must use real credit card and real purchases to try it out.
3. Must do a real refund to reset the state, which can take a few minutes.

Google please make it easier to test IAP. It's really annoying

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

[Stackoverflow](https://stackoverflow.com/questions/tagged/in-app-billing) might be a better forum.

If you think that this is a problem in the Billings library, please open a bug on the Billing public issue tracker: https://issuetracker.google.com/issues/new?component=311487&template=1014446

Please reopen if you still think this is an issue with the sample.

**Comment by AndroidDeveloperLB** [comment]
@pfmaggi Please do offer a better way to try the sample and the API in general.

**Comment by avoltis** [comment]
I think u need to use .setSkuDetails(skuDetails) instead of  .setSku(...) , 
 pass: the skuDetails object(not the entire list but the product object u want to purchase)

**Comment by AndroidDeveloperLB** [comment]
@avoltis What exactly should be used ?
Instead of this:
```
        BillingFlowParams flowParams = BillingFlowParams.newBuilder()
                .setSku(sku._skuValue)
                .setType(SkuType.INAPP)
                .build();
```
What should I write instead?

I've noticed that both `setSku` and `setType` are deprecated...

**Comment by avoltis** [comment]
@AndroidDeveloperLB   u need ```setSkuDetails```, and to pass as argument the "product object" u want to purchase, that is retrieved from ```querySkuDetailsAsync```
 ```
  BillingFlowParams flowParams = BillingFlowParams.newBuilder()
            .setSkuDetails(skuDetails)
            .build();
    int responseCode = billingClient.launchBillingFlow(activity, flowParams);
```
Keep in mind, u need to ```startConnection```, then ```querySkuDetailsAsync``` that retrieves the products u can buy from google store, then u pass one of this products as (skuDetails) and launch the purchase

https://developer.android.com/google/play/billing/billing_library_overview

**Comment by AndroidDeveloperLB** [comment]
@avoltis This is odd. Why doesn't the `querySkuDetailsAsync` get called with  `onBillingSetupFinished` , so that we get it all ready ? 
It's also odd that it doesn't get all types of SkuDetail... We really need to do 2 queries if we have IAP and subscriptions?

**Comment by avoltis** [comment]
@AndroidDeveloperLB  actually yes thats exactly like u can use it:
 "```querySkuDetailsAsync``` get called with ```onBillingSetupFinished```" 
Im not sure on how to get the all types of SkuDetail together in one go as i have not tried SUBS and INAPP in the same query.

**Comment by AndroidDeveloperLB** [comment]
@avoltis What do you mean that it "get called" ? Is it possible to get the results right away there, on the UI thread? Without doing it asynchronously ?

**Comment by avoltis** [comment]
@AndroidDeveloperLB , the query has to be asynchronous, u can do the query beforehand , and launch the billing flow (purchase) from the ui thread
this is like it looks in general:
```
private BillingClient billingClient;
...
billingClient = BillingClient.newBuilder(activity).setListener(this).build();
billingClient.startConnection(new BillingClientStateListener() {
    @Override
    public void onBillingSetupFinished(@BillingResponse int billingResponseCode) {
        if (billingResponseCode == BillingResponse.OK) {
            // The BillingClient is ready. You can query purchases here.
List<String> skuList = new ArrayList<> ();
skuList.add("premium_upgrade");
skuList.add("gas");
SkuDetailsParams.Builder params = SkuDetailsParams.newBuilder();
params.setSkusList(skuList).setType(SkuType.INAPP);
billingClient.querySkuDetailsAsync(params.build(),
    new SkuDetailsResponseListener() {
        @Override
        public void onSkuDetailsResponse(int responseCode, List<SkuDetails> skuDetailsList) {
            // Process the result.
            //with the results here (skuDetailsList), u get all the products available for purchase, pass to
           //           .setSkuDetails(skuDetails)  the product u want to buy
 
        }
    });
        }
    }
    @Override
    public void onBillingServiceDisconnected() {
        // Try to restart the connection on the next request to
        // Google Play by calling the startConnection() method.
    }
});
```

**Comment by AndroidDeveloperLB** [comment]
I see. Thank you.

**Comment by tusharpandey** [comment]
any possible ways to use getIntroDuctoryPrice()

![Screenshot 2021-06-09 at 9 21 21 PM](https://user-images.githubusercontent.com/4696846/121466277-c7f67680-c9d4-11eb-9b1d-231850bc1d4c.png)

and I am doing this to implement it.

![Screenshot 2021-06-10 at 10 15 55 AM](https://user-images.githubusercontent.com/4696846/121466322-dc3a7380-c9d4-11eb-8079-9f22e65729d0.png)
