### ISSUE TITLE
Error:This Gradle plugin requires Studio 3.0 minimum

### ISSUE THREAD

**Issue by mamert** [googlesamples/android-play-billing#98]
3.0 has "sneak peek" status.
As a workaround, replace `classpath 'com.android.tools.build:gradle:3.0.0-beta3'` in project's build.gradle with `com.android.tools.build:gradle:2.3.3`

... except then we have "Plugin with id 'com.android.feature' not found"

**Comment by gorgon** [comment]
Android Studio 3.0 is in a stable stage already.
Please find it here: https://developer.android.com/studio/index.html

**Comment by mamert** [comment]
OK, it wasn't yesterday. Closing.
